/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Kontak;

import Main.UbahAkun.UbahAkun;
import dao.DAO_Kontak;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import model.Model_Pengguna;
import service.Service_Kontak;

/**
 *
 * @author aridw
 */
public class Kontak extends javax.swing.JPanel {
    
    public Service_Kontak service = new DAO_Kontak();
    String telp;
    /**
     * Creates new form MasterBarang
     */
    public Kontak() {
        initComponents();
        
        DefaultComboBoxModel<String> comboBoxModel = (DefaultComboBoxModel<String>) cbNamaPengguna.getModel();
        List<Model_Pengguna> databaseNames = service.getData();
        for (Model_Pengguna mdp : databaseNames) {
            comboBoxModel.addElement(mdp.getNama_pengguna());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbNamaPengguna = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblJabatan = new javax.swing.JLabel();
        lblTelp = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblAlamat = new javax.swing.JTextArea();
        lblWhatsappLink = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 79, 109));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kontak");

        cbNamaPengguna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Nama Pengguna--" }));
        cbNamaPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaPenggunaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblJabatan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblJabatan.setForeground(new java.awt.Color(255, 255, 255));
        lblJabatan.setText("Jabatan");

        lblTelp.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblTelp.setText("Telepon    :");

        lblFoto.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblNama.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama");
        lblNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hubungi melalui media sosial di bawah ini!");

        jLabel7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Whatsapp :");

        jScrollPane1.setBackground(new java.awt.Color(17, 79, 109));
        jScrollPane1.setBorder(null);

        lblAlamat.setEditable(false);
        lblAlamat.setBackground(new java.awt.Color(17, 79, 109));
        lblAlamat.setColumns(20);
        lblAlamat.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setRows(5);
        lblAlamat.setText("Alamat :");
        lblAlamat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lblAlamat);

        lblWhatsappLink.setFont(new java.awt.Font("Inter", 2, 18)); // NOI18N
        lblWhatsappLink.setForeground(new java.awt.Color(0, 255, 255));
        lblWhatsappLink.setText("WhatsappWeb");
        lblWhatsappLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWhatsappLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhatsappLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblWhatsappLink, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblWhatsappLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbNamaPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaPenggunaActionPerformed
        showData();
    }//GEN-LAST:event_cbNamaPenggunaActionPerformed

    private void lblWhatsappLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhatsappLinkMouseClicked
        createLinkWA();
    }//GEN-LAST:event_lblWhatsappLinkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbNamaPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblAlamat;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTelp;
    private javax.swing.JLabel lblWhatsappLink;
    // End of variables declaration//GEN-END:variables

    private void showData(){
        String selection = (String)cbNamaPengguna.getSelectedItem();
        if(!selection.equals("--Pilih Nama Pengguna--")){
            Model_Pengguna mdp = new Model_Pengguna();
            mdp = service.getDataByNamaPengguna(selection);
            telp = mdp.getTelp_pengguna();
            lblNama.setText(mdp.getNama_pengguna());
            lblJabatan.setText(mdp.getJabatan());
            lblAlamat.setText("Alamat : " + mdp.getAlamat_pengguna());
            lblTelp.setText("Telepon    :   " + telp);
            try {
                BufferedImage bi;
                String path = mdp.getFoto();
                bi = ImageIO.read(new File(path)); 
                Image img = bi.getScaledInstance(100, 120, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lblFoto.setText("");
                lblFoto.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(UbahAkun.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void createLinkWA(){
        try {
            Desktop.getDesktop().browse(new URI("http://wa.me/+62" + telp.substring(1)));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }
}
