/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopUp;

import PreApp.Daftar;
import PreApp.Masuk;
import Main.UbahAkun.UbahAkun;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author aridw
 */
public class MenuAkun extends javax.swing.JDialog {
    private String id;
    private int initialX;
    private int initialY;
    private Frame main;
    private JPanel pnMenuUtama;
    
    /**
     * Creates new form MenuAkun
     */
    public MenuAkun(java.awt.Frame parent, boolean modal, JPanel pnUtama, String id, String nama, String jabatan, String pathFoto) {
        super(parent, modal);
        initComponents();
        this.id = id;
        this.main = parent;
        this.setLocationRelativeTo(parent);
        
        
        this.pnMenuUtama = pnUtama;
     
        try {
            BufferedImage bi = ImageIO.read(new File(pathFoto));
            Image img = bi.getScaledInstance(70, 90, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblFoto.setText("");
            lblFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblNama.setText(nama);
        lblJabatan.setText(jabatan);
    }

    private MenuAkun(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblJabatan = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKeluar = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        lblUbahAkun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnUtama.setBackground(new java.awt.Color(17, 79, 109));
        pnUtama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pnUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(17, 79, 109));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 100));

        lblFoto.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblFoto.setPreferredSize(new java.awt.Dimension(70, 90));

        lblJabatan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblJabatan.setForeground(new java.awt.Color(255, 255, 255));
        lblJabatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJabatan.setText("Jabatan");
        lblJabatan.setPreferredSize(new java.awt.Dimension(60, 60));

        lblNama.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("Nama");
        lblNama.setPreferredSize(new java.awt.Dimension(60, 60));
        lblNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNamaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnUtama.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 36, 270, 160));

        lblKeluar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        lblKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeluar.setText("Keluar");
        lblKeluar.setPreferredSize(new java.awt.Dimension(60, 60));
        lblKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKeluarMouseClicked(evt);
            }
        });
        pnUtama.add(lblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 274, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/keluar.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        pnUtama.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 7, -1, -1));

        lblUbahAkun.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblUbahAkun.setForeground(new java.awt.Color(255, 255, 255));
        lblUbahAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUbahAkun.setText("Ubah Akun");
        lblUbahAkun.setPreferredSize(new java.awt.Dimension(60, 60));
        lblUbahAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUbahAkunMouseClicked(evt);
            }
        });
        pnUtama.add(lblUbahAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 274, 30));

        getContentPane().add(pnUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNamaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNamaMouseClicked

    private void lblKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeluarMouseClicked
        this.dispose();
        main.dispose();
        new Masuk().setVisible(true);
    }//GEN-LAST:event_lblKeluarMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lblUbahAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUbahAkunMouseClicked
        pnMenuUtama.removeAll();
        pnMenuUtama.add(new UbahAkun(id, pnMenuUtama, main));
        pnMenuUtama.revalidate();
        pnMenuUtama.repaint();
        this.dispose();
    }//GEN-LAST:event_lblUbahAkunMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        initialX = evt.getX();
        initialY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int currentX = getLocation().x;
        int currentY = getLocation().y;

        int offsetX = evt.getX() - initialX;
        int offsetY = evt.getY() - initialY;

        setLocation(currentX + offsetX, currentY + offsetY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuAkun dialog = new MenuAkun(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblUbahAkun;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
