/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopUp;

import java.awt.Desktop;
import java.awt.Frame;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author aridw
 */
public class PilihVideo extends javax.swing.JDialog {
    private int initialX;
    private int initialY;
    private Frame main;
    private JPanel pnMenuUtama;
    
    /**
     * Creates new form MenuAkun
     */
    public PilihVideo(java.awt.Frame parent, boolean modal, JPanel pnUtama) {
        super(parent, modal);
        initComponents();
        this.main = parent;
        this.setLocationRelativeTo(parent);
        
        
        this.pnMenuUtama = pnUtama;
    }

    private PilihVideo(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        lblJenis = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        lblUbahAkun = new javax.swing.JLabel();
        lblBarang = new javax.swing.JLabel();
        lblDistributor = new javax.swing.JLabel();
        lblBarangMasuk = new javax.swing.JLabel();
        lblPemesanan = new javax.swing.JLabel();
        lblAkun = new javax.swing.JLabel();
        lblKeluar3 = new javax.swing.JLabel();
        lblLaporan = new javax.swing.JLabel();
        lblBarangKeluar = new javax.swing.JLabel();
        lblKontak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnUtama.setBackground(new java.awt.Color(17, 79, 109));
        pnUtama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pnUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJenis.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblJenis.setForeground(new java.awt.Color(0, 255, 255));
        lblJenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJenis.setText("Menu Jenis Barang");
        lblJenis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJenis.setPreferredSize(new java.awt.Dimension(60, 60));
        lblJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJenisMouseClicked(evt);
            }
        });
        pnUtama.add(lblJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 20));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/keluar.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        pnUtama.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 7, -1, -1));

        lblUbahAkun.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblUbahAkun.setForeground(new java.awt.Color(255, 255, 255));
        lblUbahAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUbahAkun.setText("Bantuan");
        lblUbahAkun.setPreferredSize(new java.awt.Dimension(60, 60));
        pnUtama.add(lblUbahAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 274, 30));

        lblBarang.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblBarang.setForeground(new java.awt.Color(0, 255, 255));
        lblBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBarang.setText("Menu Barang");
        lblBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBarang.setPreferredSize(new java.awt.Dimension(60, 60));
        lblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarangMouseClicked(evt);
            }
        });
        pnUtama.add(lblBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 20));

        lblDistributor.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblDistributor.setForeground(new java.awt.Color(0, 255, 255));
        lblDistributor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDistributor.setText("Menu Distributor");
        lblDistributor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDistributor.setPreferredSize(new java.awt.Dimension(60, 60));
        lblDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDistributorMouseClicked(evt);
            }
        });
        pnUtama.add(lblDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 20));

        lblBarangMasuk.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblBarangMasuk.setForeground(new java.awt.Color(0, 255, 255));
        lblBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBarangMasuk.setText("Menu Barang Masuk");
        lblBarangMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBarangMasuk.setPreferredSize(new java.awt.Dimension(60, 60));
        lblBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarangMasukMouseClicked(evt);
            }
        });
        pnUtama.add(lblBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 20));

        lblPemesanan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblPemesanan.setForeground(new java.awt.Color(0, 255, 255));
        lblPemesanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPemesanan.setText("Menu Pemesanan");
        lblPemesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPemesanan.setPreferredSize(new java.awt.Dimension(60, 60));
        lblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPemesananMouseClicked(evt);
            }
        });
        pnUtama.add(lblPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 20));

        lblAkun.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblAkun.setForeground(new java.awt.Color(0, 255, 255));
        lblAkun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAkun.setText("Mengubah Akun");
        lblAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAkun.setPreferredSize(new java.awt.Dimension(60, 60));
        lblAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAkunMouseClicked(evt);
            }
        });
        pnUtama.add(lblAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 20));

        lblKeluar3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblKeluar3.setForeground(new java.awt.Color(255, 255, 255));
        lblKeluar3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKeluar3.setText("*Klik Untuk Melihat");
        lblKeluar3.setPreferredSize(new java.awt.Dimension(60, 60));
        pnUtama.add(lblKeluar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 200, 20));

        lblLaporan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblLaporan.setForeground(new java.awt.Color(0, 255, 255));
        lblLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLaporan.setText("Menu Laporan");
        lblLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLaporan.setPreferredSize(new java.awt.Dimension(60, 60));
        lblLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLaporanMouseClicked(evt);
            }
        });
        pnUtama.add(lblLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 20));

        lblBarangKeluar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblBarangKeluar.setForeground(new java.awt.Color(0, 255, 255));
        lblBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBarangKeluar.setText("Menu Barang Keluar");
        lblBarangKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBarangKeluar.setPreferredSize(new java.awt.Dimension(60, 60));
        lblBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarangKeluarMouseClicked(evt);
            }
        });
        pnUtama.add(lblBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 20));

        lblKontak.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblKontak.setForeground(new java.awt.Color(0, 255, 255));
        lblKontak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKontak.setText("Menu Kontak");
        lblKontak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKontak.setPreferredSize(new java.awt.Dimension(60, 60));
        lblKontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKontakMouseClicked(evt);
            }
        });
        pnUtama.add(lblKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 20));

        getContentPane().add(pnUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJenisMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/ZjNZoD2d-pU"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblJenisMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        initialX = evt.getX();
        initialY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int currentX = getLocation().x;
        int currentY = getLocation().y;

        int offsetX = evt.getX() - initialX;
        int offsetY = evt.getY() - initialY;

        setLocation(currentX + offsetX, currentY + offsetY);
    }//GEN-LAST:event_formMouseDragged

    private void lblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarangMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/XjijRVgs0Mk"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblBarangMouseClicked

    private void lblDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDistributorMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/1Qkdu1O5FCA"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblDistributorMouseClicked

    private void lblBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarangMasukMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/bS2pdlyu10I"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblBarangMasukMouseClicked

    private void lblPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPemesananMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/mioxSa-o850"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblPemesananMouseClicked

    private void lblAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAkunMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/IyRYMI2Vd5k"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblAkunMouseClicked

    private void lblLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLaporanMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/MX7uiIRQFfs"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblLaporanMouseClicked

    private void lblBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarangKeluarMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/iFrfxr_hlV8"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblBarangKeluarMouseClicked

    private void lblKontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKontakMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://youtu.be/qC0AYgJXKx4"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblKontakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihVideo dialog = new PilihVideo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel lblAkun;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblBarangKeluar;
    private javax.swing.JLabel lblBarangMasuk;
    private javax.swing.JLabel lblDistributor;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblKeluar3;
    private javax.swing.JLabel lblKontak;
    private javax.swing.JLabel lblLaporan;
    private javax.swing.JLabel lblPemesanan;
    private javax.swing.JLabel lblUbahAkun;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
