/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Transaksi;

import PopUp.PilihBarang;
import PopUp.PilihDistributor;
import dao.DAO_BarangMasuk;
import dao.DAO_DetailP;
import dao.DAO_KeranjangPesan;
import dao.DAO_Laporan;
import dao.DAO_PemesananBarang;
import design.Table;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Barang;
import model.Model_DetailP;
import model.Model_Distributor;
import model.Model_KeranjangPesan;
import model.Model_Pemesanan;
import model.Model_Pengguna;
import service.Service_BarangMasuk;
import service.Service_DetailP;
import service.Service_KeranjangPesan;
import service.Service_Laporan;
import service.Service_Pemesanan;
import tablemodel.TBM_DetailP;
import tablemodel.TBM_KeranjangPesan;
import tablemodel.TBM_Pemesanan;



/**
 *
 * @author aridw
 */
public class TransaksiPemesananBarang extends javax.swing.JPanel {
    private Service_Pemesanan serviceP = new DAO_PemesananBarang();
    private Service_DetailP serviceDp = new DAO_DetailP();
    private Service_BarangMasuk serviceBM = new DAO_BarangMasuk();
    private Service_KeranjangPesan serviceKp = new DAO_KeranjangPesan();
    private Service_Laporan serviceLap = new DAO_Laporan();

    
    private TBM_Pemesanan tbmp = new TBM_Pemesanan();  
    private TBM_DetailP tbmdp = new TBM_DetailP();  
    private TBM_KeranjangPesan tbmkp = new TBM_KeranjangPesan();  
    
    private int row;
    private String idP;
   
    public TransaksiPemesananBarang(String id) {
        initComponents();
        this.idP = id;
        
        new Table().CustomTable(tabelDetail, jScrollPane1);
        new Table().CustomTable(tabelData, jScrollPane2);
        new Table().CustomTable(tabelKeranjang, jScrollPane3);
        
        tabelData.setModel(tbmp);
        tabelDetail.setModel(tbmdp);
        tabelKeranjang.setModel(tbmkp);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataPemesanan = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        pnDetail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        lblJudul2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        tambahPemesanan = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        lblTotalPemesanan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnInput = new javax.swing.JPanel();
        tfIdPemesanan = new javax.swing.JTextField();
        tfNamaDistributor = new javax.swing.JTextField();
        tfTanggalPemesanan = new javax.swing.JTextField();
        tfHargaBeli = new javax.swing.JTextField();
        tfIdDistributor = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        tfSubtotal = new javax.swing.JTextField();
        tfNamaBarang = new javax.swing.JTextField();
        tfSatuan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTambahkan = new javax.swing.JButton();
        pilBarang = new javax.swing.JTextField();
        tfIdBarang = new javax.swing.JTextField();
        pilDistributor = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataPemesanan.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Data Pemesanan Barang");

        btnTambah.setBackground(new java.awt.Color(0, 0, 100));
        btnTambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tabelData.setBackground(new java.awt.Color(240, 240, 240));
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        pnDetail.setBackground(new java.awt.Color(17, 79, 109));

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDetail);

        lblJudul2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("Detail Pesanan Barang");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/keluar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addComponent(lblJudul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul2)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );

        btnSelesai.setBackground(new java.awt.Color(0, 100, 0));
        btnSelesai.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(255, 255, 255));
        btnCetak.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(17, 79, 109));
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPemesananLayout = new javax.swing.GroupLayout(dataPemesanan);
        dataPemesanan.setLayout(dataPemesananLayout);
        dataPemesananLayout.setHorizontalGroup(
            dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataPemesananLayout.createSequentialGroup()
                        .addGroup(dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPemesananLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJudul))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPemesananLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataPemesananLayout.setVerticalGroup(
            dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dataPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPemesananLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGap(291, 291, 291)))
        );

        pnUtama.add(dataPemesanan, "card2");

        tambahPemesanan.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul1.setText("Tambah Pemesanan Barang");

        btnSimpan.setBackground(new java.awt.Color(0, 0, 100));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeranjangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKeranjang);

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 100, 0));
        btnUbah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });

        lblTotalPemesanan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblTotalPemesanan.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPemesanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalPemesanan.setText("Total Pemesanan : ");

        jLabel5.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Keranjang");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        pnInput.setBackground(new java.awt.Color(17, 79, 109));
        pnInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfIdPemesanan.setEditable(false);
        tfIdPemesanan.setBackground(new java.awt.Color(17, 79, 109));
        tfIdPemesanan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdPemesanan.setForeground(new java.awt.Color(153, 153, 153));
        tfIdPemesanan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id Pemesanan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfIdPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 55, 250, 50));

        tfNamaDistributor.setEditable(false);
        tfNamaDistributor.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaDistributor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaDistributor.setForeground(new java.awt.Color(153, 153, 153));
        tfNamaDistributor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Distributor", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfNamaDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 158, 250, 50));

        tfTanggalPemesanan.setEditable(false);
        tfTanggalPemesanan.setBackground(new java.awt.Color(17, 79, 109));
        tfTanggalPemesanan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfTanggalPemesanan.setForeground(new java.awt.Color(153, 153, 153));
        tfTanggalPemesanan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal Pemesanan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfTanggalPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 55, 250, 50));

        tfHargaBeli.setEditable(false);
        tfHargaBeli.setBackground(new java.awt.Color(17, 79, 109));
        tfHargaBeli.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfHargaBeli.setForeground(new java.awt.Color(153, 153, 153));
        tfHargaBeli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Beli", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 266, 250, 50));

        tfIdDistributor.setEditable(false);
        tfIdDistributor.setBackground(new java.awt.Color(17, 79, 109));
        tfIdDistributor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdDistributor.setForeground(new java.awt.Color(153, 153, 153));
        tfIdDistributor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id Distributor", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfIdDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 158, 210, 50));

        tfJumlah.setBackground(new java.awt.Color(17, 79, 109));
        tfJumlah.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfJumlah.setForeground(new java.awt.Color(255, 255, 255));
        tfJumlah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });
        pnInput.add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 326, 250, 50));

        tfSubtotal.setEditable(false);
        tfSubtotal.setBackground(new java.awt.Color(17, 79, 109));
        tfSubtotal.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfSubtotal.setForeground(new java.awt.Color(153, 153, 153));
        tfSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subtotal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 250, 50));

        tfNamaBarang.setEditable(false);
        tfNamaBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfNamaBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Barang", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 326, 250, 50));

        tfSatuan.setEditable(false);
        tfSatuan.setBackground(new java.awt.Color(17, 79, 109));
        tfSatuan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfSatuan.setForeground(new java.awt.Color(153, 153, 153));
        tfSatuan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Satuan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 250, 50));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pemesanan");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 30));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barang");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 226, 530, 30));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Distributor");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 530, 30));

        btnTambahkan.setBackground(new java.awt.Color(255, 255, 255));
        btnTambahkan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambahkan.setForeground(new java.awt.Color(17, 79, 109));
        btnTambahkan.setText("TAMBAHKAN");
        btnTambahkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahkanMouseClicked(evt);
            }
        });
        pnInput.add(btnTambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 520, 34));

        pilBarang.setEditable(false);
        pilBarang.setBackground(new java.awt.Color(255, 255, 255));
        pilBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pilBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pilBarang.setText("...");
        pilBarang.setBorder(null);
        pilBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilBarangMouseClicked(evt);
            }
        });
        pnInput.add(pilBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, 30));

        tfIdBarang.setEditable(false);
        tfIdBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfIdBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfIdBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id Barang", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        pilDistributor.setEditable(false);
        pilDistributor.setBackground(new java.awt.Color(255, 255, 255));
        pilDistributor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pilDistributor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pilDistributor.setText("...");
        pilDistributor.setBorder(null);
        pilDistributor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilDistributorMouseClicked(evt);
            }
        });
        pnInput.add(pilDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 40, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblTotalPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(lblTotalPemesanan)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout tambahPemesananLayout = new javax.swing.GroupLayout(tambahPemesanan);
        tambahPemesanan.setLayout(tambahPemesananLayout);
        tambahPemesananLayout.setHorizontalGroup(
            tambahPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahPemesananLayout.createSequentialGroup()
                        .addGroup(tambahPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahPemesananLayout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJudul1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahPemesananLayout.setVerticalGroup(
            tambahPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul1)
                .addGap(18, 18, 18)
                .addGroup(tambahPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(tambahPemesanan, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showPanelAddData();
        
        tfIdPemesanan.setText(serviceP.nomor());
        tfTanggalPemesanan.setText(tanggal());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDetailMouseClicked
      
    }//GEN-LAST:event_tabelDetailMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        saveData();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        row = tabelData.getSelectedRow();
        String id = tabelData.getModel().getValueAt(row, 0).toString();
        List<Model_DetailP> list = serviceDp.getById(id);
        tbmdp.setData(list);
        pnDetail.setVisible(true);
        btnSelesai.setVisible(true);
        btnCetak.setVisible(true);
    }//GEN-LAST:event_tabelDataMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        prepareDataForUpdate();
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteDataChart();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        pnDetail.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void pilDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilDistributorMouseClicked
        showPilDistributor();
    }//GEN-LAST:event_pilDistributorMouseClicked

    private void pilBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilBarangMouseClicked
        showPilBarang();
    }//GEN-LAST:event_pilBarangMouseClicked

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        subtotal();
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void btnTambahkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahkanMouseClicked
        if(tfSubtotal.getText().trim().isEmpty()){
            subtotal();
        }
        
        if(btnTambahkan.getText().equals("PERBARUI DATA")){
            updateDataCart();
        }else {
            addDataChart();
        }
    }//GEN-LAST:event_btnTambahkanMouseClicked

    private void tabelKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeranjangMouseClicked
        btnUbah.setVisible(true);
    }//GEN-LAST:event_tabelKeranjangMouseClicked

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        if(serviceP.checkStatus(tabelData.getModel().getValueAt(row, 0).toString())){
            String id_pemesanan = tabelData.getModel().getValueAt(row, 0).toString();
            serviceBM.completeTheOrder(id_pemesanan, idP);
            serviceBM.updateStokFromPemesanan(id_pemesanan);
            loadData();
        }else{
            JOptionPane.showMessageDialog(null, "Transaksi Pemesanan Sudah Selesai");
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        String id = (String) tabelData.getModel().getValueAt(row, 0);
        showReport(id);
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel dataPemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblTotalPemesanan;
    private javax.swing.JTextField pilBarang;
    private javax.swing.JTextField pilDistributor;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pnInput;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable tabelData;
    private javax.swing.JTable tabelDetail;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JPanel tambahPemesanan;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfIdBarang;
    private javax.swing.JTextField tfIdDistributor;
    private javax.swing.JTextField tfIdPemesanan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaDistributor;
    private javax.swing.JTextField tfSatuan;
    private javax.swing.JTextField tfSubtotal;
    private javax.swing.JTextField tfTanggalPemesanan;
    // End of variables declaration//GEN-END:variables
    
    private void loadData(){
        pnDetail.setVisible(false);
        btnSelesai.setVisible(false);
        btnCetak.setVisible(false);
        List<Model_Pemesanan> list = serviceP.getData();
        tbmp.setData(list);
    }
    
    private void loadCartData(){
        List<Model_KeranjangPesan> list = serviceKp.getData();
        tbmkp.setData(list);
    }
    
    private void showPanelData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataPemesanan);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    private void showPanelAddData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(tambahPemesanan);
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pilDistributor.setEnabled(true);
        serviceDp.temporaryDelete();
        resetForm();
        loadCartData();
    }
    
    private void subtotal(){
        Long jumlah, hargaBeli, subTotal;
        jumlah = Long.parseLong(tfJumlah.getText());
        hargaBeli = Long.parseLong(tfHargaBeli.getText());
        subTotal = jumlah * hargaBeli;
        
        tfSubtotal.setText(Long.toString(subTotal));
    }
    
    private String tanggal(){
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        return sdf.format(now);
    }

    private void showPilDistributor() {
        boolean closable = true;
        PilihDistributor pd = new PilihDistributor(null, closable);
        pd.setVisible(true);
        
        tfIdDistributor.setText(pd.md.getId_distributor());
        tfNamaDistributor.setText(pd.md.getNama_distributor());
        
        pilBarang.requestFocus();
    }
    
    private void showPilBarang() {
        boolean closable = true;
        PilihBarang pb = new PilihBarang(null, closable);
        pb.setVisible(true);
        
        tfIdBarang.setText(pb.mb.getId_barang());
        tfNamaBarang.setText(pb.mb.getNama_barang());
        tfHargaBeli.setText(Integer.toString(pb.mb.getHarga_beli()));
        tfSatuan.setText(pb.mb.getSatuan());
        
        pilBarang.requestFocus();
    }

    private void clearTfBarang() {
        tfIdBarang.setText("");
        tfNamaBarang.setText("");
        tfSatuan.setText("");
        tfHargaBeli.setText("");
        tfSubtotal.setText("");
        tfJumlah.setText("");
        
        pilBarang.requestFocus();
    }
    
    private void resetForm(){
        clearTfBarang();
        tfIdDistributor.setText("");
        tfNamaDistributor.setText("");
        lblTotalPemesanan.setText("Total Pemesanan : ");
    }
    
    private boolean validasiInput(){
        boolean isInputValid = false;
        if(tfIdDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Distributor Belum Dipilih");
        }else if(tfIdBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Barang Belum Dipilih");
        }else if(tfJumlah.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Tidak Boleh Kosong");
        }else{
            isInputValid = true;
        }
        return isInputValid;
    }
    
    private void addDataChart(){
        if(validasiInput()){
            String idPesan = tfIdPemesanan.getText();
            String id = tfIdBarang.getText();
            String nama = tfNamaBarang.getText();
            int jumlah = Integer.parseInt(tfJumlah.getText());
            int hargaBeli = Integer.parseInt(tfHargaBeli.getText());
            int subTotal = Integer.parseInt(tfSubtotal.getText());

            Model_Pemesanan mp = new Model_Pemesanan();
            Model_Barang mb = new Model_Barang();
            Model_DetailP mdp = new Model_DetailP();
            Model_KeranjangPesan mkp = new Model_KeranjangPesan();

            mp.setId_pemesanan(idPesan);

            mb.setId_barang(id);
            mb.setNama_barang(nama);
            mb.setHarga_beli(hargaBeli);

            mdp.setJumlah_pemesanan(jumlah);
            mdp.setSubtotal_pemesanan(subTotal);
            mdp.setStatus("Dipesan");

            mkp.setPemesanan(mp);
            mkp.setBarang(mb);
            mkp.setDetail_pemesanan(mdp);

            serviceKp.addData(mkp);
            lblTotalPemesanan.setText("Total Pemesanan : " + serviceDp.sumTotal());

            loadCartData();
            clearTfBarang();
            pilDistributor.setEnabled(false);
        }
    }
    
    private void deleteDataChart(){
        row = tabelKeranjang.getSelectedRow();
        if(row != -1){
            if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                serviceKp.deleteData(tabelKeranjang.getModel().getValueAt(row, 0).toString());
                tbmkp.deleteData(row);
                lblTotalPemesanan.setText("Total Pemesanan : " + serviceDp.sumTotal());
                loadCartData();
                clearTfBarang();
            }else{
                JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Baris Terlebih Dahulu");
        }
        
    }

    private void prepareDataForUpdate() {
        row = tabelKeranjang.getSelectedRow();
        if(row != -1){
            tfSatuan.setVisible(false);
            tfIdBarang.setText(tabelKeranjang.getModel().getValueAt(row, 0).toString());
            tfNamaBarang.setText(tabelKeranjang.getModel().getValueAt(row, 1).toString());
            tfHargaBeli.setText(tabelKeranjang.getModel().getValueAt(row, 2).toString());
            tfJumlah.setText(tabelKeranjang.getModel().getValueAt(row, 3).toString());
            tfSubtotal.setText(tabelKeranjang.getModel().getValueAt(row, 4).toString());

            btnTambahkan.setText("PERBARUI DATA");
            pilBarang.setEnabled(false);
            pilDistributor.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Baris Terlebih Dahulu");
        }
    }
    
    private void updateDataCart() {
        if(validasiInput()){
            String idPesan = tfIdPemesanan.getText();
            String tglPesan = tfTanggalPemesanan.getText();
            String idDis = tfIdDistributor.getText();
            int totPesan = Integer.parseInt(lblTotalPemesanan.getText().substring(18));
            String idPengguna = idP;
            String status = "Dipesan";

            String id = tfIdBarang.getText();
            String nama = tfNamaBarang.getText();
            int jumlah = Integer.parseInt(tfJumlah.getText());
            int hargaBeli = Integer.parseInt(tfHargaBeli.getText());
            int subTotal = Integer.parseInt(tfSubtotal.getText());

            Model_Pemesanan mp = new Model_Pemesanan();
            Model_Barang mb = new Model_Barang();
            Model_DetailP mdp = new Model_DetailP();
            Model_Distributor md = new Model_Distributor();
            Model_Pengguna mpg = new Model_Pengguna();
            Model_KeranjangPesan mkp = new Model_KeranjangPesan();

            mp.setId_pemesanan(idPesan);
            mp.setTgl_pemesanan(tglPesan);
            mp.setTotal_pemesanan(totPesan);
            mp.setStatus(status);

            mb.setId_barang(id);
            mb.setNama_barang(nama);
            mb.setHarga_beli(hargaBeli);

            md.setId_distributor(idDis);

            mpg.setId_pengguna(idPengguna);

            mp.setDistributor(md);
            mp.setPengguna(mpg);

            mdp.setPemesanan(mp);
            mdp.setBarang(mb);
            mdp.setJumlah_pemesanan(jumlah);
            mdp.setSubtotal_pemesanan(subTotal);        
            mdp.setStatus(status);

            mkp.setPemesanan(mp);
            mkp.setBarang(mb);
            mkp.setDetail_pemesanan(mdp);

            serviceKp.updateData(mkp);
            tbmkp.updateData(row, mkp);

            lblTotalPemesanan.setText("Total Pemesanan : " + serviceDp.sumTotal());

            loadCartData();
            clearTfBarang();

            btnTambahkan.setText("TAMBAHKAN");
            pilBarang.setEnabled(true);
        }
    }

    private void saveData() {
        String idPesan = tfIdPemesanan.getText();
        String tglPesan = tfTanggalPemesanan.getText();
        String idDis = tfIdDistributor.getText();
        int totPesan = Integer.parseInt(lblTotalPemesanan.getText().substring(18));
        String idPengguna = idP;
        String status = "Dipesan";

        Model_Pemesanan mp = new Model_Pemesanan();
        Model_DetailP mdp = new Model_DetailP();
        Model_Distributor md = new Model_Distributor();
        Model_Pengguna mpg = new Model_Pengguna();
    
        mp.setId_pemesanan(idPesan);
        mp.setTgl_pemesanan(tglPesan);
        mp.setTotal_pemesanan(totPesan);
        mp.setStatus(status);

        md.setId_distributor(idDis);
        
        mpg.setId_pengguna(idPengguna);
        
        mp.setDistributor(md);
        mp.setPengguna(mpg);

        serviceP.addData(mp);
        serviceDp.addData(mdp);
        
        serviceDp.temporaryDelete();
        lblTotalPemesanan.setText("Total Pemesanan : " + serviceDp.sumTotal());
        
        resetForm();
        showPanelData();
        loadData();
        showReport(idPesan);
    }
    
    private void showReport(String id) {
        int row = tabelData.getSelectedRow();
        serviceLap.laporan1PopUp("LaporanPemesananPertransaksi", id);
    }
}
