/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Transaksi;

import PopUp.PilihBarang;
import PopUp.PilihDistributor;
import dao.DAO_DetailBK;
import dao.DAO_KeranjangBK;
import dao.DAO_BarangKeluar;
import dao.DAO_Laporan;
import design.Table;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Barang;
import model.Model_DetailBK;
import model.Model_KeranjangKeluar;
import model.Model_BarangKeluar;
import model.Model_Pengguna;
import service.Service_DetailBK;
import service.Service_KeranjangKeluar;
import service.Service_BarangKeluar;
import service.Service_Laporan;
import tablemodel.TBM_DetailBK;
import tablemodel.TBM_KeranjangBK;
import tablemodel.TBM_BarangKeluar;



/**
 *
 * @author aridw
 */
public class TransaksiBarangKeluar extends javax.swing.JPanel {
    private Service_BarangKeluar serviceBK = new DAO_BarangKeluar();
    private Service_DetailBK serviceDBK = new DAO_DetailBK();
    private Service_KeranjangKeluar serviceKK = new DAO_KeranjangBK();
    private Service_Laporan serviceLap = new DAO_Laporan();

    
    private TBM_BarangKeluar tbmBK = new TBM_BarangKeluar();  
    private TBM_DetailBK tbmDBK = new TBM_DetailBK();  
    private TBM_KeranjangBK tbmKK = new TBM_KeranjangBK();  
    
    private int row;
    private String idP;
   
    public TransaksiBarangKeluar(String id) {
        initComponents();
        this.idP = id;
        
        new Table().CustomTable(tabelDetail, jScrollPane1);
        new Table().CustomTable(tabelData, jScrollPane2);
        new Table().CustomTable(tabelKeranjang, jScrollPane3);
        
        tabelData.setModel(tbmBK);
        tabelDetail.setModel(tbmDBK);
        tabelKeranjang.setModel(tbmKK);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataBarangKeluar = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        pnDetail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        lblJudul2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        tambahBarangKeluar = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        pnInput = new javax.swing.JPanel();
        tfIdBarangKeluar = new javax.swing.JTextField();
        tfTanggalBarangMasuk = new javax.swing.JTextField();
        tfHargaJual = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        tfSubtotal = new javax.swing.JTextField();
        tfNamaBarang = new javax.swing.JTextField();
        tfSatuan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambahkan = new javax.swing.JButton();
        pilBarang = new javax.swing.JTextField();
        tfIdBarang = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfKembalian = new javax.swing.JTextField();
        tfPembayaran = new javax.swing.JTextField();
        tfHargaBayar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataBarangKeluar.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Data Barang Keluar");

        btnTambah.setBackground(new java.awt.Color(0, 0, 100));
        btnTambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tabelData.setBackground(new java.awt.Color(240, 240, 240));
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        pnDetail.setBackground(new java.awt.Color(17, 79, 109));

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDetail);

        lblJudul2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("Detail Barang Keluar");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/keluar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addComponent(lblJudul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 586, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul2)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );

        btnCetak.setBackground(new java.awt.Color(255, 255, 255));
        btnCetak.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(17, 79, 109));
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangKeluarLayout = new javax.swing.GroupLayout(dataBarangKeluar);
        dataBarangKeluar.setLayout(dataBarangKeluarLayout);
        dataBarangKeluarLayout.setHorizontalGroup(
            dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                        .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJudul))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataBarangKeluarLayout.setVerticalGroup(
            dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );

        pnUtama.add(dataBarangKeluar, "card2");

        tambahBarangKeluar.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul1.setText("Tambah Transaksi Barang Keluar");

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeranjangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKeranjang);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Keranjang");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        pnInput.setBackground(new java.awt.Color(17, 79, 109));
        pnInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfIdBarangKeluar.setEditable(false);
        tfIdBarangKeluar.setBackground(new java.awt.Color(17, 79, 109));
        tfIdBarangKeluar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdBarangKeluar.setForeground(new java.awt.Color(153, 153, 153));
        tfIdBarangKeluar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id Barang Keluar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfIdBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 55, 250, 50));

        tfTanggalBarangMasuk.setEditable(false);
        tfTanggalBarangMasuk.setBackground(new java.awt.Color(17, 79, 109));
        tfTanggalBarangMasuk.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfTanggalBarangMasuk.setForeground(new java.awt.Color(153, 153, 153));
        tfTanggalBarangMasuk.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal Barang Keluar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfTanggalBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 55, 250, 50));

        tfHargaJual.setEditable(false);
        tfHargaJual.setBackground(new java.awt.Color(17, 79, 109));
        tfHargaJual.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfHargaJual.setForeground(new java.awt.Color(153, 153, 153));
        tfHargaJual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Jual", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 250, 50));

        tfJumlah.setBackground(new java.awt.Color(17, 79, 109));
        tfJumlah.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfJumlah.setForeground(new java.awt.Color(255, 255, 255));
        tfJumlah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });
        pnInput.add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, 50));

        tfSubtotal.setEditable(false);
        tfSubtotal.setBackground(new java.awt.Color(17, 79, 109));
        tfSubtotal.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfSubtotal.setForeground(new java.awt.Color(153, 153, 153));
        tfSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subtotal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 250, 50));

        tfNamaBarang.setEditable(false);
        tfNamaBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfNamaBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Barang", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 50));

        tfSatuan.setEditable(false);
        tfSatuan.setBackground(new java.awt.Color(17, 79, 109));
        tfSatuan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfSatuan.setForeground(new java.awt.Color(153, 153, 153));
        tfSatuan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Satuan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 250, 50));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang Keluar");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 30));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaksi");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 530, 30));

        btnTambahkan.setBackground(new java.awt.Color(255, 255, 255));
        btnTambahkan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambahkan.setForeground(new java.awt.Color(17, 79, 109));
        btnTambahkan.setText("TAMBAHKAN");
        btnTambahkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahkanMouseClicked(evt);
            }
        });
        pnInput.add(btnTambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 520, 34));

        pilBarang.setEditable(false);
        pilBarang.setBackground(new java.awt.Color(255, 255, 255));
        pilBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pilBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pilBarang.setText("...");
        pilBarang.setBorder(null);
        pilBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilBarangMouseClicked(evt);
            }
        });
        pnInput.add(pilBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 40, 30));

        tfIdBarang.setEditable(false);
        tfIdBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfIdBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfIdBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id Barang", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 0, 100));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SELESAI");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        pnInput.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 113, 34));

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        pnInput.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 113, 34));

        btnUbah.setBackground(new java.awt.Color(0, 100, 0));
        btnUbah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });
        pnInput.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 250, 34));

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnInput.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 380, 240, 34));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Barang");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pnInput.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 530, 30));

        tfKembalian.setEditable(false);
        tfKembalian.setBackground(new java.awt.Color(17, 79, 109));
        tfKembalian.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfKembalian.setForeground(new java.awt.Color(153, 153, 153));
        tfKembalian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kembalian", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 510, 50));

        tfPembayaran.setBackground(new java.awt.Color(17, 79, 109));
        tfPembayaran.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        tfPembayaran.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembayaran", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPembayaranActionPerformed(evt);
            }
        });
        pnInput.add(tfPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 510, 50));

        tfHargaBayar.setEditable(false);
        tfHargaBayar.setBackground(new java.awt.Color(17, 79, 109));
        tfHargaBayar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfHargaBayar.setForeground(new java.awt.Color(153, 153, 153));
        tfHargaBayar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Bayar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Inter", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnInput.add(tfHargaBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 510, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3))
            .addComponent(pnInput, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tambahBarangKeluarLayout = new javax.swing.GroupLayout(tambahBarangKeluar);
        tambahBarangKeluar.setLayout(tambahBarangKeluarLayout);
        tambahBarangKeluarLayout.setHorizontalGroup(
            tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                        .addComponent(lblJudul1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahBarangKeluarLayout.setVerticalGroup(
            tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(tambahBarangKeluar, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showPanelAddData();
        
        tfIdBarangKeluar.setText(serviceBK.nomor());
        tfTanggalBarangMasuk.setText(tanggal());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDetailMouseClicked
      
    }//GEN-LAST:event_tabelDetailMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        saveData();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        row = tabelData.getSelectedRow();
        String id = tabelData.getModel().getValueAt(row, 0).toString();
        List<Model_DetailBK> list = serviceDBK.getById(id);
        tbmDBK.setData(list);
        pnDetail.setVisible(true);
        btnCetak.setVisible(true);
    }//GEN-LAST:event_tabelDataMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        prepareDataForUpdate();
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteDataChart();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        pnDetail.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void pilBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilBarangMouseClicked
        showPilBarang();
    }//GEN-LAST:event_pilBarangMouseClicked

    private void btnTambahkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahkanMouseClicked
        if(btnTambahkan.getText().equals("PERBARUI DATA")){
            updateDataCart();
        }else {
            addDataChart();
        }
    }//GEN-LAST:event_btnTambahkanMouseClicked

    private void tabelKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeranjangMouseClicked
        btnUbah.setVisible(true);
    }//GEN-LAST:event_tabelKeranjangMouseClicked

    private void tfPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPembayaranActionPerformed
        int kembalian = Integer.parseInt(tfPembayaran.getText()) - Integer.parseInt(tfHargaBayar.getText());
        tfKembalian.setText("" + kembalian);
    }//GEN-LAST:event_tfPembayaranActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        String id = (String) tabelData.getModel().getValueAt(row, 0);
        showReport(id);
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        subtotal();
    }//GEN-LAST:event_tfJumlahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel dataBarangKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JTextField pilBarang;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pnInput;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable tabelData;
    private javax.swing.JTable tabelDetail;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JPanel tambahBarangKeluar;
    private javax.swing.JTextField tfHargaBayar;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfIdBarang;
    private javax.swing.JTextField tfIdBarangKeluar;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfPembayaran;
    private javax.swing.JTextField tfSatuan;
    private javax.swing.JTextField tfSubtotal;
    private javax.swing.JTextField tfTanggalBarangMasuk;
    // End of variables declaration//GEN-END:variables
    
    private void loadData(){
        pnDetail.setVisible(false);
        btnCetak.setVisible(false);
        List<Model_BarangKeluar> list = serviceBK.getData();
        tbmBK.setData(list);
    }
    
    private void loadCartData(){
        List<Model_KeranjangKeluar> list = serviceKK.getData();
        tbmKK.setData(list);
    }
    
    private void showPanelData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataBarangKeluar);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    private void showPanelAddData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(tambahBarangKeluar);
        pnUtama.repaint();
        pnUtama.revalidate();
        
        serviceDBK.temporaryDelete();
        resetForm();
        loadCartData();
    }
    
    private void subtotal(){
        int jumlah, hargaBeli, subTotal;
        if(tfJumlah.getText().trim().isEmpty()){
            jumlah = 0;
        }else{
            jumlah = Integer.parseInt(tfJumlah.getText());
            hargaBeli = Integer.parseInt(tfHargaJual.getText());
            subTotal = jumlah * hargaBeli;

            tfSubtotal.setText(""+subTotal);
        }
    }
    
    private String tanggal(){
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        return sdf.format(now);
    }

    
    private void showPilBarang() {
        boolean closable = true;
        PilihBarang pb = new PilihBarang(null, closable);
        pb.setVisible(true);
        
        tfIdBarang.setText(pb.mb.getId_barang());
        tfNamaBarang.setText(pb.mb.getNama_barang());
        tfHargaJual.setText(Integer.toString(pb.mb.getHarga_jual()));
        tfSatuan.setText(pb.mb.getSatuan());
        
        pilBarang.requestFocus();
    }
    
    private void resetBarang(){
        tfIdBarang.setText("");
        tfNamaBarang.setText("");
        tfSatuan.setText("");
        tfHargaJual.setText("");
        tfSubtotal.setText("");
        tfJumlah.setText("");
        
        pilBarang.requestFocus();
    }

    private void resetForm() {
        resetBarang();
        tfHargaBayar.setText("");
        tfKembalian.setText("");
        tfPembayaran.setText("");
    }
    
    private boolean validasiInput(){
        boolean isInputValid = false;
        if(tfIdBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Barang Belum Dipilih");
        }else if(tfJumlah.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Tidak Boleh Kosong");
        }else{
            isInputValid = true;
        }
        return isInputValid;
    }
    
    private void addDataChart(){
        if(validasiInput()){
            String idMasuk = tfIdBarangKeluar.getText();
            String id = tfIdBarang.getText();
            String nama = tfNamaBarang.getText();
            int jumlah = Integer.parseInt(tfJumlah.getText());
            int hargaBeli = Integer.parseInt(tfHargaJual.getText());
            int subTotal = Integer.parseInt(tfSubtotal.getText());

            Model_BarangKeluar mp = new Model_BarangKeluar();
            Model_Barang mb = new Model_Barang();
            Model_DetailBK mdBM = new Model_DetailBK();
            Model_KeranjangKeluar mkm = new Model_KeranjangKeluar();

            mp.setId_barang_keluar(idMasuk);

            mb.setId_barang(id);
            mb.setNama_barang(nama);
            mb.setHarga_jual(hargaBeli);

            mdBM.setJumlah_keluar(jumlah);
            mdBM.setSubtotal_keluar(subTotal);

            mkm.setBarang_keluar(mp);
            mkm.setBarang(mb);
            mkm.setDetail_barang_keluar(mdBM);

            if(serviceDBK.stokValidation(id, jumlah)){
                serviceKK.addData(mkm);
                tfHargaBayar.setText(Integer.toString(serviceDBK.sumTotal()));

                loadCartData();
                resetBarang();
            }else{
                JOptionPane.showMessageDialog(null, "Stok Tidak Cukup");
            }
        }
    }
    
    private void deleteDataChart(){
        row = tabelKeranjang.getSelectedRow();
        if(row != -1){
            if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                serviceKK.deleteData(tabelKeranjang.getModel().getValueAt(row, 0).toString());
                tbmKK.deleteData(row);
                tfHargaBayar.setText("" + serviceDBK.sumTotal());
                loadCartData();
                resetBarang();
            }else{
                JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Baris Terlebih Dahulu");
        }
        
    }

    private void prepareDataForUpdate() {
        row = tabelKeranjang.getSelectedRow();
        if(row != -1){
            tfSatuan.setVisible(false);
            tfIdBarang.setText(tabelKeranjang.getModel().getValueAt(row, 0).toString());
            tfNamaBarang.setText(tabelKeranjang.getModel().getValueAt(row, 1).toString());
            tfHargaJual.setText(tabelKeranjang.getModel().getValueAt(row, 2).toString());
            tfJumlah.setText(tabelKeranjang.getModel().getValueAt(row, 3).toString());
            tfSubtotal.setText(tabelKeranjang.getModel().getValueAt(row, 4).toString());

            btnTambahkan.setText("PERBARUI DATA");
            pilBarang.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Baris Terlebih Dahulu");
        }
        
    }
    
    private void updateDataCart() {
        if(validasiInput()){
            String idMasuk = tfIdBarangKeluar.getText();
            String tglMasuk = tfTanggalBarangMasuk.getText();
            int totMasuk = Integer.parseInt(tfHargaBayar.getText());
            String idPengguna = idP;

            String id = tfIdBarang.getText();
            String nama = tfNamaBarang.getText();
            int jumlah = Integer.parseInt(tfJumlah.getText());
            int hargaBeli = Integer.parseInt(tfHargaJual.getText());
            int subTotal = Integer.parseInt(tfSubtotal.getText());

            Model_BarangKeluar mbm = new Model_BarangKeluar();
            Model_Barang mb = new Model_Barang();
            Model_DetailBK mdBM = new Model_DetailBK();
            Model_Pengguna mpg = new Model_Pengguna();
            Model_KeranjangKeluar mkm = new Model_KeranjangKeluar();

            mbm.setId_barang_keluar(idMasuk);
            mbm.setTgl_keluar(tglMasuk);
            mbm.setTotalKeluar(totMasuk);

            mb.setId_barang(id);
            mb.setNama_barang(nama);
            mb.setHarga_jual(hargaBeli);

            mpg.setId_pengguna(idPengguna);

            mbm.setPengguna(mpg);

            mdBM.setBarang_keluar(mbm);
            mdBM.setBarang(mb);
            mdBM.setJumlah_keluar(jumlah);
            mdBM.setSubtotal_keluar(subTotal);        

            mkm.setBarang_keluar(mbm);
            mkm.setBarang(mb);
            mkm.setDetail_barang_keluar(mdBM);

            if(serviceDBK.stokValidation(id, jumlah)){
                serviceKK.updateData(mkm);
                tbmKK.updateData(row, mkm);

                tfHargaBayar.setText("" + serviceDBK.sumTotal());

                loadCartData();
                resetBarang();

                btnTambahkan.setText("TAMBAHKAN");
                pilBarang.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Stok Tidak Cukup");
            }
        }
    }

    private void saveData() {
        String idKeluar = tfIdBarangKeluar.getText();
        String tglKeluar = tfTanggalBarangMasuk.getText();
        int totKeluar = Integer.parseInt(tfHargaBayar.getText());
        String idPengguna = idP;

        Model_BarangKeluar mbm = new Model_BarangKeluar();
        Model_DetailBK mdBM = new Model_DetailBK();
        Model_Pengguna mpg = new Model_Pengguna();
    
        mbm.setId_barang_keluar(idKeluar);
        mbm.setTgl_keluar(tglKeluar);
        mbm.setTotalKeluar(totKeluar);

        mpg.setId_pengguna(idPengguna);
        
        mbm.setPengguna(mpg);

        serviceBK.addData(mbm);
        serviceBK.updateStok();
        serviceDBK.addData(mdBM);
        
        serviceDBK.temporaryDelete();
        tfHargaBayar.setText("" + serviceDBK.sumTotal());
        
        resetForm();
        showPanelData();
        loadData();
        showReport(idKeluar);
    }
    
    private void showReport(String id) {
        int row = tabelData.getSelectedRow();
        serviceLap.laporan1PopUp("LaporanBarangKeluarPertransaksi", id);
    }
}
