/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Laporan;

import dao.DAO_Laporan;
import service.Service_Laporan;


/**
 *
 * @author aridw
 */
public class LaporanBarang extends javax.swing.JPanel {
   
    private Service_Laporan service= new DAO_Laporan();
   
    public LaporanBarang() {
        initComponents();

        pnAction.setVisible(true);
        pnDataBarang.setVisible(false);
        pnTransaksiBarang.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataBarangMasuk = new javax.swing.JPanel();
        pnPilihJenisLaporan = new javax.swing.JPanel();
        pnAction = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        cbPilih = new javax.swing.JComboBox<>();
        pnDataBarang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        printLaporanBarang = new javax.swing.JButton();
        pnTransaksiBarang = new javax.swing.JPanel();
        printLaporanBarang1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblJudul2 = new javax.swing.JLabel();
        pnTampilLaporan = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataBarangMasuk.setBackground(new java.awt.Color(17, 79, 109));

        pnPilihJenisLaporan.setBackground(new java.awt.Color(17, 79, 109));
        pnPilihJenisLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnAction.setBackground(new java.awt.Color(17, 79, 109));
        pnAction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnAction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnPilihJenisLaporan.add(pnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        lblJudul.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudul.setText("Pilih Jenis Laporan");
        pnPilihJenisLaporan.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 244, -1));

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(17, 79, 109));
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        pnPilihJenisLaporan.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 301, 244, 34));

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Laporan--", "Laporan Stok Barang", "Laporan Transaksi Barang" }));
        cbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihActionPerformed(evt);
            }
        });
        pnPilihJenisLaporan.add(cbPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 51, 244, 38));

        pnDataBarang.setBackground(new java.awt.Color(17, 79, 109));
        pnDataBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnDataBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laporan Data Barang");
        pnDataBarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        printLaporanBarang.setBackground(new java.awt.Color(255, 255, 255));
        printLaporanBarang.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printLaporanBarang.setForeground(new java.awt.Color(17, 79, 109));
        printLaporanBarang.setText("PRINT");
        printLaporanBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printLaporanBarangMouseClicked(evt);
            }
        });
        pnDataBarang.add(printLaporanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 41, 214, 33));

        pnPilihJenisLaporan.add(pnDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        pnTransaksiBarang.setBackground(new java.awt.Color(17, 79, 109));
        pnTransaksiBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnTransaksiBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printLaporanBarang1.setBackground(new java.awt.Color(255, 255, 255));
        printLaporanBarang1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printLaporanBarang1.setForeground(new java.awt.Color(17, 79, 109));
        printLaporanBarang1.setText("PRINT");
        printLaporanBarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printLaporanBarang1MouseClicked(evt);
            }
        });
        pnTransaksiBarang.add(printLaporanBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 41, 214, 33));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Laporan Transaksi Barang");
        pnTransaksiBarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        pnPilihJenisLaporan.add(pnTransaksiBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        lblJudul2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("Laporan Barang");

        pnTampilLaporan.setBackground(new java.awt.Color(17, 79, 109));
        pnTampilLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnTampilLaporanLayout = new javax.swing.GroupLayout(pnTampilLaporan);
        pnTampilLaporan.setLayout(pnTampilLaporanLayout);
        pnTampilLaporanLayout.setHorizontalGroup(
            pnTampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        pnTampilLaporanLayout.setVerticalGroup(
            pnTampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dataBarangMasukLayout = new javax.swing.GroupLayout(dataBarangMasuk);
        dataBarangMasuk.setLayout(dataBarangMasukLayout);
        dataBarangMasukLayout.setHorizontalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPilihJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangMasukLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lblJudul2)
                    .addContainerGap(712, Short.MAX_VALUE)))
        );
        dataBarangMasukLayout.setVerticalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangMasukLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPilihJenisLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangMasukLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lblJudul2)
                    .addContainerGap(574, Short.MAX_VALUE)))
        );

        pnUtama.add(dataBarangMasuk, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        pnTampilLaporan.removeAll();
        pnTampilLaporan.repaint();
        pnTampilLaporan.revalidate();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void printLaporanBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLaporanBarangMouseClicked
        service.laporan(pnTampilLaporan, "LaporanDataBarang");
    }//GEN-LAST:event_printLaporanBarangMouseClicked

    private void cbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihActionPerformed
        String pil = (String) cbPilih.getSelectedItem();
        switch (pil){
            case "--Pilih Jenis Laporan--":
                pnAction.setVisible(true);
                pnDataBarang.setVisible(false);
                pnTransaksiBarang.setVisible(false);
                break;
            case "Laporan Stok Barang":
                pnAction.setVisible(false);
                pnDataBarang.setVisible(true);
                pnTransaksiBarang.setVisible(false);
                break;
            case "Laporan Transaksi Barang":
                pnAction.setVisible(false);
                pnDataBarang.setVisible(false);
                pnTransaksiBarang.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbPilihActionPerformed

    private void printLaporanBarang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLaporanBarang1MouseClicked
        service.laporan(pnTampilLaporan, "LaporanTransaksiBarang");
    }//GEN-LAST:event_printLaporanBarang1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JPanel dataBarangMasuk;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JPanel pnAction;
    private javax.swing.JPanel pnDataBarang;
    private javax.swing.JPanel pnPilihJenisLaporan;
    private javax.swing.JPanel pnTampilLaporan;
    private javax.swing.JPanel pnTransaksiBarang;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JButton printLaporanBarang;
    private javax.swing.JButton printLaporanBarang1;
    // End of variables declaration//GEN-END:variables
}
