/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Laporan;

import PopUp.PilihBarangMasuk;
import PopUp.PilihDistributor;
import dao.DAO_Laporan;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import service.Service_Laporan;


/**
 *
 * @author aridw
 */
public class LaporanBarangMasuk extends javax.swing.JPanel {
   
    private Service_Laporan service= new DAO_Laporan();
   
    public LaporanBarangMasuk() {
        initComponents();

        pnAction.setVisible(true);
        pnPertransaksi.setVisible(false);
        pnPerdistributor.setVisible(false);
        pnPerperiode.setVisible(false);
        pnPerbulan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataBarangMasuk = new javax.swing.JPanel();
        pnPilihJenisLaporan = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        cbPilih = new javax.swing.JComboBox<>();
        pnAction = new javax.swing.JPanel();
        pnPertransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        printPertransaksi = new javax.swing.JButton();
        tfIdBarangMasuk = new javax.swing.JTextField();
        pilihPemesanan = new javax.swing.JTextField();
        pnPerdistributor = new javax.swing.JPanel();
        printPerdistributor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfIdDistributor = new javax.swing.JTextField();
        pilihDistributor = new javax.swing.JTextField();
        pnPerperiode = new javax.swing.JPanel();
        printPerperiode = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dc2 = new com.toedter.calendar.JDateChooser();
        dc1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnPerbulan = new javax.swing.JPanel();
        printPerbulan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmonth = new com.toedter.calendar.JMonthChooser();
        cyear = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblJudul2 = new javax.swing.JLabel();
        pnTampilLaporan = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataBarangMasuk.setBackground(new java.awt.Color(17, 79, 109));

        pnPilihJenisLaporan.setBackground(new java.awt.Color(17, 79, 109));
        pnPilihJenisLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudul.setText("Pilih Jenis Laporan");
        pnPilihJenisLaporan.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 244, -1));

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(17, 79, 109));
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        pnPilihJenisLaporan.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 301, 244, 34));

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Laporan--", "Pertransaksi", "Perdistributor", "Perperiode", "Perbulan" }));
        cbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihActionPerformed(evt);
            }
        });
        pnPilihJenisLaporan.add(cbPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 51, 244, 38));

        pnAction.setBackground(new java.awt.Color(17, 79, 109));
        pnAction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnAction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnPilihJenisLaporan.add(pnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        pnPertransaksi.setBackground(new java.awt.Color(17, 79, 109));
        pnPertransaksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnPertransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laporan Pertransaksi");
        pnPertransaksi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        printPertransaksi.setBackground(new java.awt.Color(255, 255, 255));
        printPertransaksi.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printPertransaksi.setForeground(new java.awt.Color(17, 79, 109));
        printPertransaksi.setText("PRINT");
        printPertransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPertransaksiMouseClicked(evt);
            }
        });
        printPertransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPertransaksiActionPerformed(evt);
            }
        });
        pnPertransaksi.add(printPertransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 214, 33));

        tfIdBarangMasuk.setBackground(new java.awt.Color(17, 79, 109));
        tfIdBarangMasuk.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfIdBarangMasuk.setEnabled(false);
        pnPertransaksi.add(tfIdBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        pilihPemesanan.setEditable(false);
        pilihPemesanan.setBackground(new java.awt.Color(255, 255, 255));
        pilihPemesanan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pilihPemesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pilihPemesanan.setText("...");
        pilihPemesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilihPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihPemesananMouseClicked(evt);
            }
        });
        pnPertransaksi.add(pilihPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, 30));

        pnPilihJenisLaporan.add(pnPertransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        pnPerdistributor.setBackground(new java.awt.Color(17, 79, 109));
        pnPerdistributor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnPerdistributor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printPerdistributor.setBackground(new java.awt.Color(255, 255, 255));
        printPerdistributor.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printPerdistributor.setForeground(new java.awt.Color(17, 79, 109));
        printPerdistributor.setText("PRINT");
        printPerdistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPerdistributorMouseClicked(evt);
            }
        });
        pnPerdistributor.add(printPerdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 214, 33));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Laporan Perdistributor");
        pnPerdistributor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        tfIdDistributor.setBackground(new java.awt.Color(17, 79, 109));
        tfIdDistributor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdDistributor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfIdDistributor.setEnabled(false);
        pnPerdistributor.add(tfIdDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        pilihDistributor.setEditable(false);
        pilihDistributor.setBackground(new java.awt.Color(255, 255, 255));
        pilihDistributor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pilihDistributor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pilihDistributor.setText("...");
        pilihDistributor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilihDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihDistributorMouseClicked(evt);
            }
        });
        pnPerdistributor.add(pilihDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, 30));

        pnPilihJenisLaporan.add(pnPerdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        pnPerperiode.setBackground(new java.awt.Color(17, 79, 109));
        pnPerperiode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnPerperiode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printPerperiode.setBackground(new java.awt.Color(255, 255, 255));
        printPerperiode.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printPerperiode.setForeground(new java.awt.Color(17, 79, 109));
        printPerperiode.setText("PRINT");
        printPerperiode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPerperiodeMouseClicked(evt);
            }
        });
        pnPerperiode.add(printPerperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 214, 33));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Laporan Perperiode");
        pnPerperiode.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));
        pnPerperiode.add(dc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 22));
        pnPerperiode.add(dc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 22));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sampai Tanggal");
        pnPerperiode.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dari Tanggal");
        pnPerperiode.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        pnPilihJenisLaporan.add(pnPerperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        pnPerbulan.setBackground(new java.awt.Color(17, 79, 109));
        pnPerbulan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnPerbulan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printPerbulan.setBackground(new java.awt.Color(255, 255, 255));
        printPerbulan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        printPerbulan.setForeground(new java.awt.Color(17, 79, 109));
        printPerbulan.setText("PRINT");
        printPerbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPerbulanMouseClicked(evt);
            }
        });
        pnPerbulan.add(printPerbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 214, 33));

        jLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Laporan Transaksi Barang");
        pnPerbulan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));
        pnPerbulan.add(cmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        pnPerbulan.add(cyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 100, 60, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tahun");
        pnPerbulan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bulan");
        pnPerbulan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        pnPilihJenisLaporan.add(pnPerbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 97, 244, 190));

        lblJudul2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("Laporan Barang Masuk");

        pnTampilLaporan.setBackground(new java.awt.Color(17, 79, 109));
        pnTampilLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnTampilLaporanLayout = new javax.swing.GroupLayout(pnTampilLaporan);
        pnTampilLaporan.setLayout(pnTampilLaporanLayout);
        pnTampilLaporanLayout.setHorizontalGroup(
            pnTampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        pnTampilLaporanLayout.setVerticalGroup(
            pnTampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dataBarangMasukLayout = new javax.swing.GroupLayout(dataBarangMasuk);
        dataBarangMasuk.setLayout(dataBarangMasukLayout);
        dataBarangMasukLayout.setHorizontalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPilihJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangMasukLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lblJudul2)
                    .addContainerGap(578, Short.MAX_VALUE)))
        );
        dataBarangMasukLayout.setVerticalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangMasukLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPilihJenisLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataBarangMasukLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lblJudul2)
                    .addContainerGap(574, Short.MAX_VALUE)))
        );

        pnUtama.add(dataBarangMasuk, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        pnTampilLaporan.removeAll();
        pnTampilLaporan.repaint();
        pnTampilLaporan.revalidate();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void printPertransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPertransaksiMouseClicked
        if(!tfIdBarangMasuk.getText().trim().isEmpty()){
            service.laporan1(pnTampilLaporan, "LaporanBarangMasukPertransaksi", tfIdBarangMasuk.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Transaksi Barang Masuk Terlebih Dahulu");
        }
    }//GEN-LAST:event_printPertransaksiMouseClicked

    private void cbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihActionPerformed
        String pil = (String) cbPilih.getSelectedItem();
        switch (pil){
            case "--Pilih Jenis Laporan--":
                pnAction.setVisible(true);
                pnPertransaksi.setVisible(false);
                pnPerdistributor.setVisible(false);
                pnPerperiode.setVisible(false);
                pnPerbulan.setVisible(false);
                break;
            case "Pertransaksi":
                pnAction.setVisible(false);
                pnPertransaksi.setVisible(true);
                pnPerdistributor.setVisible(false);
                pnPerperiode.setVisible(false);
                pnPerbulan.setVisible(false);
                break;
            case "Perdistributor":
                pnAction.setVisible(false);
                pnPertransaksi.setVisible(false);
                pnPerdistributor.setVisible(true);
                pnPerperiode.setVisible(false);
                pnPerbulan.setVisible(false);
                break;
            case "Perperiode":
                pnAction.setVisible(false);
                pnPertransaksi.setVisible(false);
                pnPerdistributor.setVisible(false);
                pnPerperiode.setVisible(true);
                pnPerbulan.setVisible(false);
                break;
            case "Perbulan":
                pnAction.setVisible(false);
                pnPertransaksi.setVisible(false);
                pnPerdistributor.setVisible(false);
                pnPerperiode.setVisible(false);
                pnPerbulan.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbPilihActionPerformed

    private void printPerdistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPerdistributorMouseClicked
        if(!tfIdDistributor.getText().trim().isEmpty()){
            service.laporan1(pnTampilLaporan, "LaporanBarangMasukPerdistributor", tfIdDistributor.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Distributor Terlebih Dahulu");
        }
    }//GEN-LAST:event_printPerdistributorMouseClicked

    private void printPerperiodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPerperiodeMouseClicked
        if(!(dc1.getDate() == null && dc2.getDate() == null)){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 

            String start = dateFormat.format(dc1.getDate());
            String end = dateFormat.format(dc2.getDate());
            service.laporan2(pnTampilLaporan, "LaporanBarangMasukPerperiode", start, end);

        }else{
            JOptionPane.showMessageDialog(null, "Pilih Tanggal Terlebih Dahulu");
        }
    }//GEN-LAST:event_printPerperiodeMouseClicked

    private void printPerbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPerbulanMouseClicked
        if(!(cyear.getYear()== -1 && cmonth.getMonth() == -1)){
            int selectedMonth = cmonth.getMonth();
            Calendar calendar = Calendar.getInstance();
            calendar.set(Calendar.MONTH, selectedMonth);

            SimpleDateFormat monthFormat = new SimpleDateFormat("MM");
            String month = monthFormat.format(calendar.getTime());
            String year = Integer.toString(cyear.getYear());
            String param = year + "-" + month + "%";
            service.laporan1(pnTampilLaporan, "LaporanBarangMasukPerbulan", param);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih Tanggal Terlebih Dahulu");
        }
    }//GEN-LAST:event_printPerbulanMouseClicked

    private void pilihPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihPemesananMouseClicked
        showPilBarangMasuk();
    }//GEN-LAST:event_pilihPemesananMouseClicked

    private void pilihDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihDistributorMouseClicked
        showPilDistributor();
    }//GEN-LAST:event_pilihDistributorMouseClicked

    private void printPertransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPertransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printPertransaksiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbPilih;
    private com.toedter.calendar.JMonthChooser cmonth;
    private com.toedter.calendar.JYearChooser cyear;
    private javax.swing.JPanel dataBarangMasuk;
    private com.toedter.calendar.JDateChooser dc1;
    private com.toedter.calendar.JDateChooser dc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JTextField pilihDistributor;
    private javax.swing.JTextField pilihPemesanan;
    private javax.swing.JPanel pnAction;
    private javax.swing.JPanel pnPerbulan;
    private javax.swing.JPanel pnPerdistributor;
    private javax.swing.JPanel pnPerperiode;
    private javax.swing.JPanel pnPertransaksi;
    private javax.swing.JPanel pnPilihJenisLaporan;
    private javax.swing.JPanel pnTampilLaporan;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JButton printPerbulan;
    private javax.swing.JButton printPerdistributor;
    private javax.swing.JButton printPerperiode;
    private javax.swing.JButton printPertransaksi;
    private javax.swing.JTextField tfIdBarangMasuk;
    private javax.swing.JTextField tfIdDistributor;
    // End of variables declaration//GEN-END:variables

    private void showPilBarangMasuk() {
        boolean closable = true;
        PilihBarangMasuk pp = new PilihBarangMasuk(null, closable);
        pp.setVisible(true);
        
        String id = pp.mbm.getId_barang_masuk();
        tfIdBarangMasuk.setText(id);
    }
    
    private void showPilDistributor() {
        boolean closable = true;
        PilihDistributor pd = new PilihDistributor(null, closable);
        pd.setVisible(true);
        
        String id = pd.md.getId_distributor();
        tfIdDistributor.setText(id);
    }
}
