/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UbahAkun;


import Main.Dasbor.Dasbor;
import PreApp.Masuk;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Model_Pengguna;
import service.Service_UbahAkun;

/**
 *
 * @author aridw
 */
public class UbahAkun extends javax.swing.JPanel {
    
    private Service_UbahAkun service = new dao.DAO_UbahAkun();
    private String fotoPath = null, nama = null, id = null, jabatan = null;
    private JPanel pnMenuUtama;
    private Frame menuUtama;
    
    public UbahAkun(String id, JPanel pnMenuUtama, Frame MenuUtama) {
        initComponents();
        this.id = id;
        this.pnMenuUtama = pnMenuUtama;
        this.menuUtama = MenuUtama;
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        ubahAkunPengguna = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfNamaPengguna = new javax.swing.JTextField();
        namaUsaha1 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        namaUsaha2 = new javax.swing.JLabel();
        tfTelp = new javax.swing.JTextField();
        namaUsaha3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        namaUsaha4 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        namaUsaha5 = new javax.swing.JLabel();
        namaUsaha6 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        namaUsaha8 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        ubahAkunPengguna.setBackground(new java.awt.Color(17, 79, 109));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ubah Akun Pengguna");

        btnSimpan.setBackground(new java.awt.Color(0, 100, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNamaPengguna.setEditable(false);
        tfNamaPengguna.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaPengguna.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaPengguna.setForeground(new java.awt.Color(153, 153, 153));
        tfNamaPengguna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfNamaPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 62, 867, 41));

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Nama Pengguna");
        jPanel1.add(namaUsaha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 130, 30));

        tfAlamat.setEditable(false);
        tfAlamat.setBackground(new java.awt.Color(17, 79, 109));
        tfAlamat.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(153, 153, 153));
        tfAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 116, 867, 41));

        namaUsaha2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha2.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha2.setText("Alamat");
        jPanel1.add(namaUsaha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 121, 130, 30));

        tfTelp.setBackground(new java.awt.Color(17, 79, 109));
        tfTelp.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfTelp.setForeground(new java.awt.Color(255, 255, 255));
        tfTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 170, 867, 41));

        namaUsaha3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha3.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha3.setText("Telepon");
        jPanel1.add(namaUsaha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, 130, 30));

        tfUsername.setBackground(new java.awt.Color(17, 79, 109));
        tfUsername.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 224, 867, 41));

        namaUsaha4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha4.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha4.setText("Username");
        jPanel1.add(namaUsaha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 229, 130, 30));

        tfPassword.setBackground(new java.awt.Color(17, 79, 109));
        tfPassword.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 278, 867, 41));

        namaUsaha5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha5.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha5.setText("Password");
        jPanel1.add(namaUsaha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 283, 130, 30));

        namaUsaha6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha6.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha6.setText("Foto");
        jPanel1.add(namaUsaha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 332, 130, 30));

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(17, 79, 109));
        tfId.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfId.setForeground(new java.awt.Color(153, 153, 153));
        tfId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 8, 867, 41));

        namaUsaha8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha8.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha8.setText("ID");
        jPanel1.add(namaUsaha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 130, 30));

        lblFoto.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblFoto.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 332, -1, -1));

        btnBrowse.setBackground(new java.awt.Color(255, 255, 255));
        btnBrowse.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(17, 79, 109));
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 452, 100, 30));

        javax.swing.GroupLayout ubahAkunPenggunaLayout = new javax.swing.GroupLayout(ubahAkunPengguna);
        ubahAkunPengguna.setLayout(ubahAkunPenggunaLayout);
        ubahAkunPenggunaLayout.setHorizontalGroup(
            ubahAkunPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahAkunPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubahAkunPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ubahAkunPenggunaLayout.createSequentialGroup()
                        .addGroup(ubahAkunPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(ubahAkunPenggunaLayout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 666, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ubahAkunPenggunaLayout.setVerticalGroup(
            ubahAkunPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahAkunPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(ubahAkunPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(ubahAkunPengguna, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        back();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        browse();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        save();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JLabel namaUsaha2;
    private javax.swing.JLabel namaUsaha3;
    private javax.swing.JLabel namaUsaha4;
    private javax.swing.JLabel namaUsaha5;
    private javax.swing.JLabel namaUsaha6;
    private javax.swing.JLabel namaUsaha8;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNamaPengguna;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfTelp;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JPanel ubahAkunPengguna;
    // End of variables declaration//GEN-END:variables

    private void loadData(){
        Model_Pengguna mdPengguna = service.getById(id);
        jabatan = mdPengguna.getJabatan();
        nama = mdPengguna.getNama_pengguna();
        tfId.setText(mdPengguna.getId_pengguna());
        tfNamaPengguna.setText(nama);
        tfAlamat.setText(mdPengguna.getAlamat_pengguna());
        tfTelp.setText(mdPengguna.getTelp_pengguna());
        tfUsername.setText(mdPengguna.getUsername());
        tfPassword.setText(mdPengguna.getPassword());
        fotoPath = mdPengguna.getFoto();
        try {
            BufferedImage bi = ImageIO.read(new File(fotoPath));
            Image img = bi.getScaledInstance(100, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblFoto.setText("");
            lblFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(UbahAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
    private void save(){
        if(validasiInput()){
            Model_Pengguna mdPengguna = new Model_Pengguna();
            mdPengguna.setNama_pengguna(tfNamaPengguna.getText());
            mdPengguna.setAlamat_pengguna(tfAlamat.getText());
            mdPengguna.setTelp_pengguna(tfTelp.getText());
            mdPengguna.setUsername(tfUsername.getText());
            mdPengguna.setPassword(tfPassword.getText());
            mdPengguna.setFoto(fotoPath);
            mdPengguna.setId_pengguna(tfId.getText());

            service.updateData(mdPengguna);
            menuUtama.dispose();
            new Masuk().setVisible(true);
        }
    }
    
    private boolean validasiInput(){
        boolean valid = false;
        if(tfNamaPengguna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
        }else if(tfAlamat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
        }else if(tfTelp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
        }else if(tfUsername.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
        }else if(tfPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
        }else if(fotoPath == null){
            JOptionPane.showMessageDialog(null, "Foto Tidak Boleh Kosong");
        }else{
            valid = true;
        }
        return valid;
    }
    
    private void back(){
        pnMenuUtama.removeAll();
        pnMenuUtama.add(new Dasbor(id));
        pnMenuUtama.repaint();
        pnMenuUtama.revalidate();    
    }
    
    public void browse(){
        BufferedImage bi;
        try {
            fotoPath = service.JChooser();
            bi = ImageIO.read(new File(fotoPath)); 
            Image img = bi.getScaledInstance(100, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblFoto.setText("");
            lblFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(UbahAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
}

