/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Master;

import PopUp.PilihJenisBarang;
import dao.DAO_JenisBarang;
import design.Table;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Barang;
import model.Model_Jenis;
import service.Service_Barang;
import service.Service_JenisBarang;
import tablemodel.TBM_Barang;



/**
 *
 * @author aridw
 */
public class MasterBarang extends javax.swing.JPanel {
    private Service_Barang service = new dao.DAO_Barang();
    private TBM_Barang tbm = new tablemodel.TBM_Barang();  
    private int row;
   
    public MasterBarang() {
        initComponents();
        
        new Table().CustomTable(tabel, jScrollPane1);
        tabel.setModel(tbm);

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        tambahBarang = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfIdBarang = new javax.swing.JTextField();
        namaUsaha = new javax.swing.JLabel();
        tfIdJenisBarang = new javax.swing.JTextField();
        namaUsaha1 = new javax.swing.JLabel();
        namaUsaha2 = new javax.swing.JLabel();
        tfNamaJenisBarang = new javax.swing.JTextField();
        tfNamaBarang = new javax.swing.JTextField();
        namaUsaha3 = new javax.swing.JLabel();
        tfHargaBeli = new javax.swing.JTextField();
        namaUsaha4 = new javax.swing.JLabel();
        namaUsaha5 = new javax.swing.JLabel();
        tfSatuan = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        namaUsaha6 = new javax.swing.JLabel();
        namaUsaha7 = new javax.swing.JLabel();
        tfHargaJual = new javax.swing.JTextField();
        btnPilihBarang = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Data Barang");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        btnTambah.setBackground(new java.awt.Color(0, 0, 100));
        btnTambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 100, 0));
        btnUbah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataBarangLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJudul))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnUtama.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(17, 79, 109));

        lblJudul1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul1.setText("Tambah Data Barang");

        btnSimpan.setBackground(new java.awt.Color(0, 100, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfIdBarang.setEditable(false);
        tfIdBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfIdBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfIdBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 13, 870, 41));

        namaUsaha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha.setText("Id Barang");
        jPanel1.add(namaUsaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 130, 30));

        tfIdJenisBarang.setEditable(false);
        tfIdJenisBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfIdJenisBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdJenisBarang.setForeground(new java.awt.Color(153, 153, 153));
        tfIdJenisBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(tfIdJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 67, 821, 41));

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Id Jenis Barang");
        jPanel1.add(namaUsaha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 130, 30));

        namaUsaha2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha2.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha2.setText("Nama Jenis Barang");
        jPanel1.add(namaUsaha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 130, 30));

        tfNamaJenisBarang.setEditable(false);
        tfNamaJenisBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaJenisBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaJenisBarang.setForeground(new java.awt.Color(255, 255, 255));
        tfNamaJenisBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfNamaJenisBarang.setEnabled(false);
        jPanel1.add(tfNamaJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 121, 870, 41));

        tfNamaBarang.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaBarang.setForeground(new java.awt.Color(255, 255, 255));
        tfNamaBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 175, 870, 41));

        namaUsaha3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha3.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha3.setText("Nama Barang ");
        jPanel1.add(namaUsaha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 130, 30));

        tfHargaBeli.setBackground(new java.awt.Color(17, 79, 109));
        tfHargaBeli.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfHargaBeli.setForeground(new java.awt.Color(255, 255, 255));
        tfHargaBeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 283, 870, 41));

        namaUsaha4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha4.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha4.setText("Satuan");
        jPanel1.add(namaUsaha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 234, 130, 30));

        namaUsaha5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha5.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha5.setText("Harga Beli");
        jPanel1.add(namaUsaha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, 130, 30));

        tfSatuan.setBackground(new java.awt.Color(17, 79, 109));
        tfSatuan.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfSatuan.setForeground(new java.awt.Color(255, 255, 255));
        tfSatuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 229, 870, 41));

        tfStok.setBackground(new java.awt.Color(17, 79, 109));
        tfStok.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfStok.setForeground(new java.awt.Color(255, 255, 255));
        tfStok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 391, 870, 41));

        namaUsaha6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha6.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha6.setText("Stok");
        jPanel1.add(namaUsaha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 396, 130, 30));

        namaUsaha7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha7.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha7.setText("Harga Jual");
        jPanel1.add(namaUsaha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 342, 130, 30));

        tfHargaJual.setBackground(new java.awt.Color(17, 79, 109));
        tfHargaJual.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfHargaJual.setForeground(new java.awt.Color(255, 255, 255));
        tfHargaJual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(tfHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 337, 870, 41));

        btnPilihBarang.setEditable(false);
        btnPilihBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnPilihBarang.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnPilihBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btnPilihBarang.setText("...");
        btnPilihBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilihBarang.setEnabled(false);
        btnPilihBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihBarangMouseClicked(evt);
            }
        });
        jPanel1.add(btnPilihBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 67, 50, 41));

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJudul1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul1)
                .addGap(18, 18, 18)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(tambahBarang, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showPanelAddData();
        resetForm();
        lblJudul1.setText("Tambah Data Barang");
        tfIdBarang.setText(service.nomor());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        btnHapus.setVisible(true);
        btnUbah.setVisible(true);
    }//GEN-LAST:event_tabelMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if(btnSimpan.getText().equals("PERBARUI")){
            updateData();
            lblJudul1.setText("Tambah Data Barang");
            btnSimpan.setText("SIMPAN");
        }else{
            saveData();
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        deleteData();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        getData();
        showPanelAddData();
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnPilihBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihBarangMouseClicked
        showPilihJenis();
    }//GEN-LAST:event_btnPilihBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JTextField btnPilihBarang;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel namaUsaha;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JLabel namaUsaha2;
    private javax.swing.JLabel namaUsaha3;
    private javax.swing.JLabel namaUsaha4;
    private javax.swing.JLabel namaUsaha5;
    private javax.swing.JLabel namaUsaha6;
    private javax.swing.JLabel namaUsaha7;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable tabel;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfIdBarang;
    private javax.swing.JTextField tfIdJenisBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaJenisBarang;
    private javax.swing.JTextField tfSatuan;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables
    
    private void loadData(){
        btnHapus.setVisible(false);
        btnUbah.setVisible(false);
        List<Model_Barang> list = service.getData();
        tbm.setData(list);
    }
    
    private void showPanelData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataBarang);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    private void showPanelAddData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(tambahBarang);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    public void resetForm(){
        tfIdJenisBarang.setText("");
        tfNamaJenisBarang.setText("");
        tfNamaBarang.setText("");
        tfSatuan.setText("");
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfStok.setText("");
    }
    
    private Model_Barang getDataFromInput(){
        String idb = tfIdBarang.getText();
        String idj = tfIdJenisBarang.getText();
        String namaj = tfNamaJenisBarang.getText();
        String namab = tfNamaBarang.getText();
        String satuan = tfSatuan.getText();
        int hargab = Integer.parseInt(tfHargaBeli.getText());
        int hargaj = Integer.parseInt(tfHargaJual.getText());
        int stok = Integer.parseInt(tfStok.getText());
        
        Model_Barang mdB = new Model_Barang();
        Model_Jenis mdJb = new Model_Jenis();
        mdJb.setId_jenis(idj);
        mdJb.setNama_jenis(namaj);
        
        mdB.setId_barang(idb);
        mdB.setNama_barang(namab);
        mdB.setSatuan(satuan);
        mdB.setHarga_beli(hargab);
        mdB.setHarga_jual(hargaj);
        mdB.setStok(stok);
        mdB.setjenis(mdJb);
        
        return mdB;
    }
    
    private void saveData(){
        if(validasiInput()){
            service.addData(getDataFromInput());
            tbm.addData(getDataFromInput());
            resetForm();
            loadData();
            showPanelData();
        }
    }
    
    private void updateData(){
        if(validasiInput()){
            service.updateData(getDataFromInput());
            tbm.updateData(row ,getDataFromInput());
            resetForm();
            loadData();
            showPanelData();
        }
    }
    
    private boolean validasiInput(){
        boolean isInputValid = false;
        if(tfIdJenisBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jenis Barang Tidak Boleh Kosong");
        }else if(tfNamaBarang.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Barang Tidak Boleh Kosong");
        }else if(tfSatuan.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Satuan Tidak Boleh Kosong");
        }else if(tfHargaBeli.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Beli Tidak Boleh Kosong");
        }else if(tfHargaJual.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Jual Tidak Boleh Kosong");
        }else if(tfStok.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Stok Tidak Boleh Kosong");
        }else{
            isInputValid = true;
        }
        return isInputValid;
    }
    
    private void deleteData(){
        row = tabel.getSelectedRow();
        if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            service.deleteData(tabel.getModel().getValueAt(row, 0).toString());
            tbm.deleteData(row);
            loadData();
            resetForm();
        }else{
            JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
        }
    }
    
    private void getData(){
        row = tabel.getSelectedRow();
        
        Model_Barang mdB = service.getById(tabel.getModel().getValueAt(row, 0).toString());
        Model_Jenis mdJb = new DAO_JenisBarang().getById(mdB.getJenis().getId_jenis());
        
        tfIdBarang.setText(mdB.getId_barang());
        tfIdJenisBarang.setText(mdJb.getId_jenis());
        tfNamaJenisBarang.setText(mdJb.getNama_jenis());
        tfNamaBarang.setText(mdB.getNama_barang());
        tfSatuan.setText(mdB.getSatuan());
        tfHargaBeli.setText(Integer.toString(mdB.getHarga_beli()));
        tfHargaJual.setText(Integer.toString(mdB.getHarga_jual()));
        tfStok.setText(Integer.toString(mdB.getStok()));
        
        lblJudul1.setText("Ubah Data Barang");
        btnSimpan.setText("PERBARUI");
    }
    
    private void showPilihJenis(){
        boolean closable = true;
        PilihJenisBarang pjb = new PilihJenisBarang(null, closable);
        pjb.setVisible(true);
        
        tfIdJenisBarang.setText(pjb.mjb.getId_jenis());
        tfNamaJenisBarang.setText(pjb.mjb.getNama_jenis());
        
        tfNamaBarang.requestFocus();
    }
}
