/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Master;

import dao.DAO_Pengguna;
import design.Table;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Jenis;
import model.Model_Pengguna;
import service.Service_Pengguna;
import tablemodel.TBM_Pengguna;

/**
 *
 * @author aridw
 */
public class MasterPengguna extends javax.swing.JPanel {
    private Service_Pengguna service = new DAO_Pengguna();
    private TBM_Pengguna tbm = new TBM_Pengguna();
    
    public MasterPengguna() {
        initComponents();
        
        new Table().CustomTable(tabel, jScrollPane1);
        tabel.setModel(tbm);
        
        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataPengguna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataPengguna.setBackground(new java.awt.Color(17, 79, 109));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Pengguna");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Aktif", "Tidak Aktif" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPenggunaLayout = new javax.swing.GroupLayout(dataPengguna);
        dataPengguna.setLayout(dataPenggunaLayout);
        dataPenggunaLayout.setHorizontalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dataPenggunaLayout.createSequentialGroup()
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataPenggunaLayout.setVerticalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnUtama.add(dataPengguna, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        deleteData();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        btnHapus.setVisible(true);
        changeCbSelected();
    }//GEN-LAST:event_tabelMouseClicked

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        updateStatus();
    }//GEN-LAST:event_cbStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JPanel dataPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void loadData(){
        btnHapus.setVisible(false);
        List<Model_Pengguna> list = service.getData();
        tbm.setData(list);
    }
    
    private void updateStatus(){
        int row = tabel.getSelectedRow();
        String id = tabel.getModel().getValueAt(row, 0).toString();
        String nama = tabel.getModel().getValueAt(row, 7).toString();
        String username = tabel.getModel().getValueAt(row, 7).toString();
        String password = tabel.getModel().getValueAt(row, 7).toString();
        String telp = tabel.getModel().getValueAt(row, 7).toString();
        String alamat = tabel.getModel().getValueAt(row, 7).toString();
        String jabatan = tabel.getModel().getValueAt(row, 7).toString();
        
        
        if(tabel.getModel().getValueAt(row, 7).toString().equals((String) cbStatus.getSelectedItem())){
        } else {
            String status = (String) cbStatus.getSelectedItem();
            Model_Pengguna mdp = new Model_Pengguna();
            mdp.setId_pengguna(id);
            mdp.setStatus(status);
            service.updateData(mdp);
            tbm.updateData(row, mdp);
            loadData();
        }
    }
    
    private void deleteData(){
        int row = tabel.getSelectedRow();
        if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            service.deleteData(tabel.getModel().getValueAt(row, 0).toString());
            tbm.deleteData(row);
            loadData();
        }else{
            JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
        }
    }
    
    private void changeCbSelected(){
        int row = tabel.getSelectedRow();
        cbStatus.setSelectedItem(tabel.getModel().getValueAt(row, 7).toString());
    }
}
