/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Master;

import dao.DAO_Distributor;
import design.Table;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Distributor;
import service.Service_Distributor;
import tablemodel.TBM_Distributor;

/**
 *
 * @author aridw
 */
public class MasterDistributor extends javax.swing.JPanel {
 
    private Service_Distributor service = new DAO_Distributor();
    private TBM_Distributor tbm = new TBM_Distributor();
    
    public MasterDistributor() {
        initComponents();
        
        new Table().CustomTable(tabel, jScrollPane1);
        tabel.setModel(tbm);
        
        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataDistributor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        tambahDistributor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfId = new javax.swing.JTextField();
        namaUsaha = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        namaUsaha1 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        namaUsaha2 = new javax.swing.JLabel();
        namaUsaha3 = new javax.swing.JLabel();
        tfTelp = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataDistributor.setBackground(new java.awt.Color(17, 79, 109));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Distributor");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        btnTambah.setBackground(new java.awt.Color(0, 0, 100));
        btnTambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataDistributorLayout = new javax.swing.GroupLayout(dataDistributor);
        dataDistributor.setLayout(dataDistributorLayout);
        dataDistributorLayout.setHorizontalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                    .addGroup(dataDistributorLayout.createSequentialGroup()
                        .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dataDistributorLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataDistributorLayout.setVerticalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnUtama.add(dataDistributor, "card2");

        tambahDistributor.setBackground(new java.awt.Color(17, 79, 109));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah Data Distributor");

        btnSimpan.setBackground(new java.awt.Color(0, 100, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(17, 79, 109));
        tfId.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfId.setForeground(new java.awt.Color(153, 153, 153));
        tfId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        namaUsaha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha.setText("Id Distributor");

        tfNama.setBackground(new java.awt.Color(17, 79, 109));
        tfNama.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(255, 255, 255));
        tfNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Nama Distributor");

        tfAlamat.setBackground(new java.awt.Color(17, 79, 109));
        tfAlamat.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(255, 255, 255));
        tfAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        namaUsaha2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha2.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha2.setText("Alamat Distributor");

        namaUsaha3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha3.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha3.setText("Telepon Distributor");

        tfTelp.setBackground(new java.awt.Color(17, 79, 109));
        tfTelp.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfTelp.setForeground(new java.awt.Color(255, 255, 255));
        tfTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(tfId, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaUsaha1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(tfNama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaUsaha2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(tfAlamat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaUsaha3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(tfTelp)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(namaUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(namaUsaha1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(namaUsaha2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(namaUsaha3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDistributorLayout = new javax.swing.GroupLayout(tambahDistributor);
        tambahDistributor.setLayout(tambahDistributorLayout);
        tambahDistributorLayout.setHorizontalGroup(
            tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahDistributorLayout.createSequentialGroup()
                        .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(tambahDistributorLayout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 611, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahDistributorLayout.setVerticalGroup(
            tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(tambahDistributor, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(tambahDistributor);
        pnUtama.repaint();
        pnUtama.revalidate();

        tfId.setText(service.nomor());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelData();
        resetForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        saveData();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        deleteData();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        btnHapus.setVisible(true);
    }//GEN-LAST:event_tabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel dataDistributor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaUsaha;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JLabel namaUsaha2;
    private javax.swing.JLabel namaUsaha3;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable tabel;
    private javax.swing.JPanel tambahDistributor;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTelp;
    // End of variables declaration//GEN-END:variables

     
    private void loadData(){
        btnHapus.setVisible(false);
        List<Model_Distributor> list = service.getData();
        tbm.setData(list);
    }
    
    private void saveData(){
        String id = tfId.getText();
        String nama = tfNama.getText();
        String telp = tfTelp.getText();
        String alamat = tfAlamat.getText();
        
        Model_Distributor mdd = new Model_Distributor();
        mdd.setId_distributor(id);
        mdd.setNama_distributor(nama);
        mdd.setTelp_distributor(telp);
        mdd.setAlamat_distributor(alamat);
        if(validasiInput()){
            service.addData(mdd);
            tbm.addData(mdd);
            resetForm();
            loadData();
            showPanelData();
        }
    }
    
    private boolean validasiInput(){
        boolean isInputValid = false;
        if(tfNama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Distributor Tidak Boleh Kosong");
        }else if(tfTelp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Telp Distributor Tidak Boleh Kosong");
        }else if(tfAlamat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Distributor Tidak Boleh Kosong");
        }else{
            isInputValid = true;
        }
        return isInputValid;
    }
    
    private void showPanelData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataDistributor);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    private void resetForm() {
        tfNama.setText("");
        tfTelp.setText("");
        tfAlamat.setText("");
    }
    
    private void deleteData(){
        int row = tabel.getSelectedRow();
        if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            service.deleteData(tabel.getModel().getValueAt(row, 0).toString());
            tbm.deleteData(row);
            loadData();
            resetForm();
        }else{
            JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
        }
    }
}
