/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Master;

import design.Table;

import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Jenis;
import service.Service_JenisBarang;
import tablemodel.TBM_Jenis;

/**
 *
 * @author aridw
 */
public class MasterJenisBarang extends javax.swing.JPanel {
    
    private Service_JenisBarang service = new dao.DAO_JenisBarang();
    private TBM_Jenis tbm = new tablemodel.TBM_Jenis();
    
    public MasterJenisBarang() {
        initComponents();
        
        new Table().CustomTable(table, jScrollPane2);
        table.setModel(tbm);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUtama = new javax.swing.JPanel();
        dataJenisBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tambahJenisBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfIdJenis = new javax.swing.JTextField();
        namaUsaha = new javax.swing.JLabel();
        tfNamaJenis = new javax.swing.JTextField();
        namaUsaha1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 618));
        setLayout(new java.awt.CardLayout());

        pnUtama.setLayout(new java.awt.CardLayout());

        dataJenisBarang.setBackground(new java.awt.Color(17, 79, 109));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Jenis Barang");

        btnTambah.setBackground(new java.awt.Color(0, 0, 100));
        btnTambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(100, 0, 0));
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout dataJenisBarangLayout = new javax.swing.GroupLayout(dataJenisBarang);
        dataJenisBarang.setLayout(dataJenisBarangLayout);
        dataJenisBarangLayout.setHorizontalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(dataJenisBarangLayout.createSequentialGroup()
                        .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dataJenisBarangLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 730, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataJenisBarangLayout.setVerticalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(dataJenisBarang, "card2");

        tambahJenisBarang.setBackground(new java.awt.Color(17, 79, 109));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah Data Jenis Barang");

        btnSimpan.setBackground(new java.awt.Color(0, 100, 0));
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(100, 0, 0));
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 79, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfIdJenis.setBackground(new java.awt.Color(17, 79, 109));
        tfIdJenis.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfIdJenis.setForeground(new java.awt.Color(153, 153, 153));
        tfIdJenis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tfIdJenis.setEnabled(false);
        jPanel1.add(tfIdJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 13, 864, 41));

        namaUsaha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha.setText("Id Jenis Barang");
        jPanel1.add(namaUsaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 130, 30));

        tfNamaJenis.setBackground(new java.awt.Color(17, 79, 109));
        tfNamaJenis.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNamaJenis.setForeground(new java.awt.Color(255, 255, 255));
        tfNamaJenis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfNamaJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaJenisActionPerformed(evt);
            }
        });
        jPanel1.add(tfNamaJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 67, 864, 41));

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Nama Jenis Barang");
        jPanel1.add(namaUsaha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 130, 30));

        javax.swing.GroupLayout tambahJenisBarangLayout = new javax.swing.GroupLayout(tambahJenisBarang);
        tambahJenisBarang.setLayout(tambahJenisBarangLayout);
        tambahJenisBarangLayout.setHorizontalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                        .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 567, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahJenisBarangLayout.setVerticalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUtama.add(tambahJenisBarang, "card2");

        add(pnUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(tambahJenisBarang);
        pnUtama.repaint();
        pnUtama.revalidate();
        
        tfIdJenis.setText(service.nomor());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataJenisBarang);
        pnUtama.repaint();
        pnUtama.revalidate();
        
        resetForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tfNamaJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaJenisActionPerformed
        showPanelData();
    }//GEN-LAST:event_tfNamaJenisActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        saveData();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        btnHapus.setVisible(true);
    }//GEN-LAST:event_tableMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        deleteData();
    }//GEN-LAST:event_btnHapusMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel dataJenisBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namaUsaha;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTable table;
    private javax.swing.JPanel tambahJenisBarang;
    private javax.swing.JTextField tfIdJenis;
    private javax.swing.JTextField tfNamaJenis;
    // End of variables declaration//GEN-END:variables

    
    private void loadData(){
        btnHapus.setVisible(false);
        List<Model_Jenis> list = service.getData();
        tbm.setData(list);
    }
    
    private void saveData(){
        String id = tfIdJenis.getText();
        String nama = tfNamaJenis.getText();
        
        Model_Jenis mdJb = new Model_Jenis();
        mdJb.setId_jenis(id);
        mdJb.setNama_jenis(nama);
        if(service.validasiNamaJenisBarang(mdJb)){
            if(validasiInput()){
                service.addData(mdJb);
                tbm.addData(mdJb);
                resetForm();
                loadData();
                showPanelData();
            }
        }
    }
    
    private boolean validasiInput(){
        boolean isInputValid = false;
        if(tfNamaJenis.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Jenis Barang Tidak Boleh Kosong");
        }else{
            isInputValid = true;
        }
        return isInputValid;
    }
    
    private void showPanelData(){
        pnUtama.removeAll();
        pnUtama.repaint();
        pnUtama.revalidate();
        
        pnUtama.add(dataJenisBarang);
        pnUtama.repaint();
        pnUtama.revalidate();
    }
    
    private void resetForm() {
        tfIdJenis.setText("");
        tfNamaJenis.setText("");
    }
    
    private void deleteData(){
        int row = table.getSelectedRow();
        if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            service.deleteData(table.getModel().getValueAt(row, 0).toString());
            tbm.deleteData(row);
            loadData();
            resetForm();
        }else{
            JOptionPane.showMessageDialog(null, "Operasi Dibatalkan Pengguna");
        }
    }
}
