/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PreApp;

import Main.UbahAkun.UbahAkun;
import dao.DAO_Daftar;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Model_Pengguna;
import service.Service_Daftar;


/**
 *
 * @author aridw
 */
public class Daftar extends javax.swing.JFrame {
    private Service_Daftar service = new DAO_Daftar();
    public static boolean tutup = false;
    private String path = null, jabatan = null;
    /**
     * Creates new form Masuk
     */
    public Daftar() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnUtama = new javax.swing.JPanel();
        namaUsaha = new javax.swing.JLabel();
        namaUsaha2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        namaUsaha3 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        namaUsaha1 = new javax.swing.JLabel();
        namaUsaha5 = new javax.swing.JLabel();
        tfTelp = new javax.swing.JTextField();
        namaUsaha6 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        namaUsaha7 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        namaUsaha8 = new javax.swing.JLabel();
        namaUsaha9 = new javax.swing.JLabel();
        dropdown = new javax.swing.JComboBox<>();
        namaUsaha10 = new javax.swing.JLabel();
        tfVerif = new javax.swing.JTextField();
        btnDaftar = new javax.swing.JButton();
        linkMasuk = new javax.swing.JLabel();
        namaUsaha12 = new javax.swing.JLabel();
        namaUsaha13 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnUtama.setBackground(new java.awt.Color(20, 99, 135));
        pnUtama.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnUtama.setLayout(new java.awt.GridBagLayout());

        namaUsaha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha, gridBagConstraints);

        namaUsaha2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        namaUsaha2.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha2.setText("Mufti Aquarian Official");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 20, 0, 0);
        pnUtama.add(namaUsaha2, gridBagConstraints);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo/logo60.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setMinimumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 60, 0, 0);
        pnUtama.add(logo, gridBagConstraints);

        namaUsaha3.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        namaUsaha3.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha3.setText("Daftar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 0);
        pnUtama.add(namaUsaha3, gridBagConstraints);

        browse.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        browse.setForeground(new java.awt.Color(20, 99, 135));
        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        pnUtama.add(browse, gridBagConstraints);

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha1, gridBagConstraints);

        namaUsaha5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha5.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha5.setText("Telepon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha5, gridBagConstraints);

        tfTelp.setBackground(new java.awt.Color(20, 99, 135));
        tfTelp.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfTelp.setForeground(new java.awt.Color(255, 255, 255));
        tfTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfTelp, gridBagConstraints);

        namaUsaha6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha6.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha6.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha6, gridBagConstraints);

        tfAlamat.setBackground(new java.awt.Color(20, 99, 135));
        tfAlamat.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(255, 255, 255));
        tfAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfAlamat, gridBagConstraints);

        namaUsaha7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha7.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha7.setText("Jabatan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 76, 0, 0);
        pnUtama.add(namaUsaha7, gridBagConstraints);

        tfNama.setBackground(new java.awt.Color(20, 99, 135));
        tfNama.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(255, 255, 255));
        tfNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfNama, gridBagConstraints);

        namaUsaha8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        namaUsaha8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaUsaha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ornamen.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 16;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 54, 0, 0);
        pnUtama.add(namaUsaha8, gridBagConstraints);

        namaUsaha9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha9.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha9.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha9, gridBagConstraints);

        dropdown.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jabatan--", "Super Admin", "Owner", "Staff" }));
        dropdown.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 0, 110);
        pnUtama.add(dropdown, gridBagConstraints);

        namaUsaha10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha10.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha10.setText("Verifikasi Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha10, gridBagConstraints);

        tfVerif.setBackground(new java.awt.Color(20, 99, 135));
        tfVerif.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfVerif.setForeground(new java.awt.Color(255, 255, 255));
        tfVerif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfVerif, gridBagConstraints);

        btnDaftar.setBackground(new java.awt.Color(255, 255, 255));
        btnDaftar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(20, 99, 135));
        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 427;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 76, 66, 110);
        pnUtama.add(btnDaftar, gridBagConstraints);

        linkMasuk.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        linkMasuk.setForeground(new java.awt.Color(0, 255, 255));
        linkMasuk.setText("masuk disini");
        linkMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMasukMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        pnUtama.add(linkMasuk, gridBagConstraints);

        namaUsaha12.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha12.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha12.setText("Foto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 76, 0, 0);
        pnUtama.add(namaUsaha12, gridBagConstraints);

        namaUsaha13.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha13.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha13.setText("Sudah mempunyai akun ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 174, 0, 0);
        pnUtama.add(namaUsaha13, gridBagConstraints);

        lblFoto.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblFoto.setPreferredSize(new java.awt.Dimension(100, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 17;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 0);
        pnUtama.add(lblFoto, gridBagConstraints);

        tfUsername.setBackground(new java.awt.Color(20, 99, 135));
        tfUsername.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfUsername, gridBagConstraints);

        tfPassword.setBackground(new java.awt.Color(20, 99, 135));
        tfPassword.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 348;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 0, 110);
        pnUtama.add(tfPassword, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMasukMouseClicked
        this.dispose();
        new Masuk().setVisible(true);
    }//GEN-LAST:event_linkMasukMouseClicked

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        prosesDaftar();
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        BufferedImage bi;
        try {
            path = service.JChooser();
            bi = ImageIO.read(new File(path)); 
            Image img = bi.getScaledInstance(100, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblFoto.setText("");
            lblFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(UbahAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel linkMasuk;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel namaUsaha;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JLabel namaUsaha10;
    private javax.swing.JLabel namaUsaha12;
    private javax.swing.JLabel namaUsaha13;
    private javax.swing.JLabel namaUsaha2;
    private javax.swing.JLabel namaUsaha3;
    private javax.swing.JLabel namaUsaha5;
    private javax.swing.JLabel namaUsaha6;
    private javax.swing.JLabel namaUsaha7;
    private javax.swing.JLabel namaUsaha8;
    private javax.swing.JLabel namaUsaha9;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfTelp;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfVerif;
    // End of variables declaration//GEN-END:variables

    private void prosesDaftar(){
        if(validasiInput() == true && validasiPassword() == true){
            jabatan = (String) dropdown.getSelectedItem();
            String nama = tfNama.getText();
            String pw = tfPassword.getText();
            String user = tfUsername.getText();
            String telp = tfTelp.getText();
            String alamat = tfAlamat.getText();
            
            String id = service.nomor(jabatan);

            
            model.Model_Pengguna mdPengguna = new Model_Pengguna();
            
            mdPengguna.setId_pengguna(id);
            mdPengguna.setNama_pengguna(nama);
            mdPengguna.setPassword(pw);
            mdPengguna.setUsername(user);
            mdPengguna.setTelp_pengguna(telp);
            mdPengguna.setAlamat_pengguna(alamat);
            mdPengguna.setJabatan(jabatan);
            mdPengguna.setFoto(path);
            mdPengguna.setStatus("Menunggu");
            
            service.addData(mdPengguna);
            if(tutup){
                this.dispose();
            }
        }
    }
    
     private boolean validasiInput(){
        boolean valid = false;
        if(dropdown.getSelectedItem().equals("--Pilih Jabatan--")){
            JOptionPane.showMessageDialog(null, "Pilih Jabatan Terlebih Dahulu");
        }else if(tfNama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
        }else if(tfUsername.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
        }else if(tfPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
        }else if(tfVerif.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Verifikasi Password Tidak Boleh Kosong");
        }else if(tfTelp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
        }else if(tfAlamat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
        }else if(path == null){
            JOptionPane.showMessageDialog(null, "Foto Tidak Boleh Kosong");
        }else{
            valid = true;
        }
        return valid;
    }
    
    private boolean validasiPassword(){
        boolean verify = false;
        if(tfPassword.getText().equals(tfVerif.getText())){
            verify = true;
        }else{
            JOptionPane.showMessageDialog(null, "Verifikasi Password Salah");
        }
        return verify;
    }
}
