/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PreApp;

import javax.swing.JOptionPane;
import model.Model_Login;
import service.Service_Login;


/**
 *
 * @author aridw
 */
public class Masuk extends javax.swing.JFrame {

    private Service_Login service = new dao.DAO_Masuk();
    public static boolean tutup = false;
    /**
     * Creates new form Masuk
     */
    public Masuk() {
        initComponents();
        
        tfUsername.requestFocus();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    private boolean validasiInput(){
        boolean valid = false;
        if(tfUsername.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
        }else if(tfPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
        }else{
            valid = true;
        }
        return valid;
    }

    private void prosesLogin(){
        if(validasiInput() == true){
            String id = tfUsername.getText();
            String user = tfUsername.getText();
            String pw = tfPassword.getText();
            
            model.Model_Login mdLogin = new Model_Login();
            
            mdLogin.setIdPengguna(id);
            mdLogin.setUser(user);
            mdLogin.setPw(pw);
            
            service.prosesLogin(mdLogin);
            if(tutup){
                this.dispose();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnUtama = new javax.swing.JPanel();
        namaUsaha = new javax.swing.JLabel();
        namaUsaha2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        namaUsaha3 = new javax.swing.JLabel();
        namaUsaha1 = new javax.swing.JLabel();
        namaUsaha8 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        btnMasuk = new javax.swing.JButton();
        linkDaftar = new javax.swing.JLabel();
        namaUsaha13 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnUtama.setBackground(new java.awt.Color(20, 99, 135));
        pnUtama.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnUtama.setLayout(new java.awt.GridBagLayout());

        namaUsaha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(260, 80, 0, 0);
        pnUtama.add(namaUsaha, gridBagConstraints);

        namaUsaha2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        namaUsaha2.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha2.setText("Mufti Aquarian Official");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        pnUtama.add(namaUsaha2, gridBagConstraints);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo/logo60.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setMinimumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 60, 0, 0);
        pnUtama.add(logo, gridBagConstraints);

        namaUsaha3.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        namaUsaha3.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha3.setText("Masuk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(190, 80, 0, 0);
        pnUtama.add(namaUsaha3, gridBagConstraints);

        namaUsaha1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha1.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 80, 0, 0);
        pnUtama.add(namaUsaha1, gridBagConstraints);

        namaUsaha8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        namaUsaha8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaUsaha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ornamen.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 80, 0, 0);
        pnUtama.add(namaUsaha8, gridBagConstraints);

        tfPassword.setBackground(new java.awt.Color(20, 99, 135));
        tfPassword.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 344;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnUtama.add(tfPassword, gridBagConstraints);

        btnMasuk.setBackground(new java.awt.Color(255, 255, 255));
        btnMasuk.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(20, 99, 135));
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 419;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 86);
        pnUtama.add(btnMasuk, gridBagConstraints);

        linkDaftar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        linkDaftar.setForeground(new java.awt.Color(0, 255, 255));
        linkDaftar.setText("daftar disini");
        linkDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDaftarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 170, 0);
        pnUtama.add(linkDaftar, gridBagConstraints);

        namaUsaha13.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        namaUsaha13.setForeground(new java.awt.Color(255, 255, 255));
        namaUsaha13.setText("Belum mempunyai akun ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 170, 0);
        pnUtama.add(namaUsaha13, gridBagConstraints);

        tfUsername.setBackground(new java.awt.Color(20, 99, 135));
        tfUsername.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 344;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(260, 0, 0, 0);
        pnUtama.add(tfUsername, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDaftarMouseClicked
        Daftar daftar = new Daftar();
        daftar.setVisible(true);
        daftar.revalidate();

        this.dispose();
    }//GEN-LAST:event_linkDaftarMouseClicked

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        prosesLogin();
    }//GEN-LAST:event_btnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel linkDaftar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel namaUsaha;
    private javax.swing.JLabel namaUsaha1;
    private javax.swing.JLabel namaUsaha13;
    private javax.swing.JLabel namaUsaha2;
    private javax.swing.JLabel namaUsaha3;
    private javax.swing.JLabel namaUsaha8;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
